-- TAWASLO MIGRATION — STEP 1 (v2)
-- Run this in the OLD project SQL editor. It only reads your data (the helper function is temporary and disappears).
-- It returns ONE cell containing the full migration script for the new project.
create or replace function pg_temp.tw_table_json(q text) returns text language plpgsql as $f$
declare r text;
begin
  execute format('select coalesce(json_agg(x), ''[]''::json)::text from %s x', q) into r;
  return r;
end $f$;

with
exts as (
  select 'create extension if not exists "uuid-ossp" with schema extensions;' || E'\n' ||
         'create extension if not exists pgcrypto with schema extensions;' as s
),
seqs as (
  select string_agg(format('create sequence if not exists public.%I;', s.relname), E'\n') as s
  from pg_class s join pg_namespace n on n.oid = s.relnamespace
  where n.nspname = 'public' and s.relkind = 'S'
    and not exists (select 1 from pg_depend d where d.objid = s.oid and d.deptype = 'i')
),
funcs as (
  select string_agg(pg_get_functiondef(p.oid) || ';', E'\n\n') as s
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f','p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
),
tbls as (
  select string_agg(ddl, E'\n\n' order by relname) as s from (
    select c.relname, format('create table public.%I (%s);', c.relname,
      string_agg(format('%I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
        case when a.attidentity = 'a' then ' generated always as identity'
             when a.attidentity = 'd' then ' generated by default as identity'
             when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
             when ad.adbin is not null then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
             else '' end,
        case when a.attnotnull then ' not null' else '' end), ', ' order by a.attnum)) as ddl
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
    left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
    where n.nspname = 'public' and c.relkind = 'r'
    group by c.relname
  ) x
),
seqown as (
  select string_agg(format('alter sequence public.%I owned by public.%I.%I;', s.relname, t.relname, a.attname), E'\n') as s
  from pg_depend d join pg_class s on s.oid = d.objid and s.relkind = 'S'
  join pg_class t on t.oid = d.refobjid
  join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
  join pg_namespace n on n.oid = s.relnamespace
  where n.nspname = 'public' and d.deptype = 'a'
),
cons as (
  select string_agg(format('alter table public.%I add constraint %I %s;', c.relname, co.conname, pg_get_constraintdef(co.oid)), E'\n' order by c.relname, co.contype desc) as s
  from pg_constraint co join pg_class c on c.oid = co.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and co.contype in ('p','u','c','x')
),
idx as (
  select string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n') as s
  from pg_index i join pg_class c on c.oid = i.indrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not exists (select 1 from pg_constraint co where co.conindid = i.indexrelid)
),
datarows as (
  select string_agg(stmt, E'\n' order by ord, qname) as s from (
    select 1 as ord, 'auth.users' as qname,
      format($t$do $twmig8x2q$ declare j json := %L; cols text; begin if json_array_length(j) = 0 then return; end if; select string_agg(quote_ident(attname), ', ' order by attnum) into cols from pg_attribute where attrelid = 'auth.users'::regclass and attnum > 0 and not attisdropped and attgenerated = '' and attname in (select json_object_keys(j->0)); execute format('insert into auth.users (%%1$s) overriding system value select %%1$s from json_populate_recordset(null::auth.users, $1)', cols) using j; end $twmig8x2q$;$t$,
        (select coalesce(json_agg(u), '[]'::json) from auth.users u)::text) as stmt
    union all
    select 2, 'auth.identities',
      format($t$do $twmig8x2q$ declare j json := %L; cols text; begin if json_array_length(j) = 0 then return; end if; select string_agg(quote_ident(attname), ', ' order by attnum) into cols from pg_attribute where attrelid = 'auth.identities'::regclass and attnum > 0 and not attisdropped and attgenerated = '' and attname in (select json_object_keys(j->0)); execute format('insert into auth.identities (%%1$s) overriding system value select %%1$s from json_populate_recordset(null::auth.identities, $1)', cols) using j; end $twmig8x2q$;$t$,
        (select coalesce(json_agg(i), '[]'::json) from auth.identities i)::text)
    union all
    select 3, t.qname,
      format($t$do $twmig8x2q$ declare j json := %L; cols text; begin if json_array_length(j) = 0 then return; end if; select string_agg(quote_ident(attname), ', ' order by attnum) into cols from pg_attribute where attrelid = %L::regclass and attnum > 0 and not attisdropped and attgenerated = '' and attname in (select json_object_keys(j->0)); execute format('insert into %s (%%1$s) overriding system value select %%1$s from json_populate_recordset(null::%s, $1)', cols) using j; end $twmig8x2q$;$t$,
        pg_temp.tw_table_json(t.qname),
        t.qname, t.qname, t.qname)
    from (select format('public.%I', c.relname) as qname from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relkind = 'r') t
  ) d
),
fks as (
  select string_agg(format('alter table public.%I add constraint %I %s;', c.relname, co.conname, pg_get_constraintdef(co.oid)), E'\n') as s
  from pg_constraint co join pg_class c on c.oid = co.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and co.contype = 'f'
),
rls as (
  select string_agg(format('alter table public.%I enable row level security;', c.relname)
    || case when c.relforcerowsecurity then format(' alter table public.%I force row level security;', c.relname) else '' end, E'\n') as s
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
pols as (
  select string_agg(case when schemaname = 'storage'
      then format('do $sp$ begin execute %L; exception when others then raise notice %L; end $sp$;', stmt, 'storage policy skipped: ' || policyname)
      else stmt end, E'\n') as s
  from (
    select schemaname, policyname, format('create policy %I on %I.%I as %s for %s to %s%s%s;', policyname, schemaname, tablename, permissive, cmd,
      (select string_agg(case when r = 'public' then 'public' else quote_ident(r) end, ', ') from unnest(roles) r),
      case when qual is not null then ' using (' || qual || ')' else '' end,
      case when with_check is not null then ' with check (' || with_check || ')' else '' end) as stmt
    from pg_policies where schemaname in ('public','storage')
  ) p
),
bkt as (
  select string_agg(format('do $bk$ begin execute %L; exception when others then raise notice %L; end $bk$;',
    format('insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values (%L, %L, %L, %L, %L) on conflict (id) do nothing', id, name, public, file_size_limit, allowed_mime_types),
    'bucket skipped: ' || id), E'\n') as s
  from storage.buckets
),
pub as (
  select string_agg(format('alter publication supabase_realtime add table %I.%I;', schemaname, tablename), E'\n') as s
  from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public'
)
select concat_ws(E'\n\n',
  '-- TAWASLO MIGRATION — STEP 2: run this whole script in the NEW project. It runs as one transaction (all or nothing).',
  'set check_function_bodies = off;',
  (select s from exts), (select s from seqs), (select s from tbls), (select s from seqown),
  (select s from cons), (select s from idx), (select s from funcs), (select s from datarows), (select s from fks), (select s from rls),
  (select s from pols), (select s from bkt), (select s from pub),
  $fin$do $seq$ declare r record; m bigint; sq text; begin for r in select c.relname, a.attname from pg_attribute a join pg_class c on c.oid = a.attrelid join pg_namespace n on n.oid = c.relnamespace left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum where n.nspname = 'public' and c.relkind = 'r' and a.attnum > 0 and not a.attisdropped and (a.attidentity in ('a','d') or pg_get_expr(ad.adbin, ad.adrelid) like 'nextval(%') loop sq := pg_get_serial_sequence(format('public.%I', r.relname), r.attname); if sq is null then continue; end if; execute format('select max(%I) from public.%I', r.attname, r.relname) into m; if m is not null then perform setval(sq, m); end if; end loop; end $seq$;$fin$,
  $fin$select 'MIGRATION COMPLETE' as status, (select count(*) from auth.users) as users, (select count(*) from information_schema.tables where table_schema = 'public') as tables;$fin$
) as migration_script;
