import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ArrowRight, ArrowUpRight, Bookmark, Check, Copy, CreditCard, Image, Lightbulb, Moon, PenLine, Sparkles, Sun, Upload, X } from 'lucide-react';
import { Artwork } from './CalendarExperience';
import { canPublishOnWeb } from './workspaceResponsive';
import { DEFAULT_STUDIO_FIELDS, STUDIO_PRESETS, captionText, readStudioSaved, saveStudioItem, stageStudioCaption } from './studioPreviewModel';
import { STUDIO_FORMATS, STUDIO_FORMAT_DEFAULTS, studioCanvas, dimensionLabel, readStudioImage, resetInvalidCustomSize } from './studioFormats';
import './ai-studio-experience.css';

const TOOLS=[['captions','Captions',PenLine,'Find the right words.'],['ideas','Post ideas',Lightbulb,'Find a fresh angle.'],['images','Images',Image,'Picture the direction.']];
const PLATFORMS=[['ig','Instagram'],['fb','Facebook'],['li','LinkedIn'],['tt','TikTok'],['tw','X'],['yt','YouTube']];
const AI_CREDIT_PACKS=[['Lite',50,'$20.90'],['Plus',100,'$26.90'],['Max',250,'$42.90']];
const AI_CREDIT_TOPUPS=[[50,'$14.90'],[100,'$24.90'],[250,'$49.90']];
const isAvailableTool=key=>TOOLS.some(([id])=>id===key);
const toolName=key=>TOOLS.find(([id])=>id===key)?.[1]||'Studio';
const defaultResult=fields=>({fields:{...fields},selected:fields.tone==='Direct'?1:fields.tone==='Story-led'?2:0,edits:{}});

function Field({label,children,hint}){return <label className="st-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function FormatControls({fields,update,source,loading,images}) {
  const canvas=studioCanvas(fields),editing=images&&fields.imageMode==='edit';
  return <>
    <fieldset className="st-choice-group st-formats" disabled={loading}><legend>Format</legend><div>
      {editing&&<button type="button" className="st-original-format" aria-pressed={fields.ratio==='original'} disabled={!source} onClick={()=>update('ratio','original')}><Image size={20} aria-hidden="true"/><span>Original size<small>{source?dimensionLabel(source):'Choose an image to detect its size'}</small></span>{fields.ratio==='original'&&<Check size={16} aria-hidden="true"/>}</button>}
      {STUDIO_FORMATS.map(item=><button type="button" key={item.id} aria-pressed={fields.ratio===item.id} onClick={()=>update('ratio',item.id)}><span className="st-format-shape" style={{width:item.width>=item.height?24:24*item.width/item.height,height:item.height>=item.width?24:24*item.height/item.width}} aria-hidden="true"/><span>{item.label}<small>{item.id} · {dimensionLabel(item)}</small></span></button>)}
      {images&&<button type="button" aria-pressed={fields.ratio==='custom'} onClick={()=>update('ratio','custom')}><PenLine size={20} aria-hidden="true"/><span>Custom size<small>Set width and height</small></span></button>}
    </div></fieldset>
    {images&&fields.ratio==='custom'&&<div className="st-custom-size"><div className="st-field-grid"><Field label="Width (px)"><input type="number" inputMode="numeric" min="16" max="8192" step="1" value={fields.customWidth} onChange={e=>update('customWidth',e.target.value===''?'':Number(e.target.value))} aria-invalid={!canvas} aria-describedby="st-custom-help"/></Field><Field label="Height (px)"><input type="number" inputMode="numeric" min="16" max="8192" step="1" value={fields.customHeight} onChange={e=>update('customHeight',e.target.value===''?'':Number(e.target.value))} aria-invalid={!canvas} aria-describedby="st-custom-help"/></Field></div><p id="st-custom-help" className={canvas?'st-result-note':'st-error'} role={canvas?undefined:'alert'}>Use whole numbers from 16 to 8,192 pixels per side.</p></div>}
    {canvas&&<p className="st-size-summary" role="status"><strong>{canvas.label}</strong><span>{dimensionLabel(canvas)} · {canvas.ratio}</span>{editing&&source&&<small>Source: {dimensionLabel(source)}. The original file stays unchanged.</small>}{editing&&!source&&fields.ratio==='original'&&<small>Saved dimensions only. Choose a source image to continue editing.</small>}</p>}
    {editing&&source&&canvas&&source.width*canvas.height!==source.height*canvas.width&&<fieldset className="st-choice-group"><legend>Framing</legend><div>{[['contain','Fit whole image'],['cover','Fill frame (crop)']].map(([id,label])=><button key={id} type="button" aria-pressed={fields.imageFit===id} onClick={()=>update('imageFit',id)}>{label}</button>)}</div><p className="st-result-note">{fields.imageFit==='cover'?'Centered crop preview. Parts outside the frame are hidden, not deleted.':'Keeps the whole image visible. Extra space is shown around it when the shape differs.'}</p></fieldset>}
  </>;
}
export default function AIStudioExperience({dark=false,setDark=()=>{},mobileWeb=false,onOpenPublisher=()=>{},onBuyAiCredits=()=>{},aiCredits={used:0,remaining:5,limit:5,extra:0,packName:'Trial',planName:'Trial',allowanceLabel:'5 shared AI credits',allowancePending:false,unlimited:false},initialTool='captions',initialSavedId='',onInitialSavedOpened=()=>{}}) {
  const [tool,setTool]=useState(isAvailableTool(initialTool)?initialTool:'captions');
  const [fields,setFields]=useState({...DEFAULT_STUDIO_FIELDS});
  const [results,setResults]=useState({captions:defaultResult(DEFAULT_STUDIO_FIELDS)});
  const [saved,setSaved]=useState(()=>readStudioSaved());
  const [savedView,setSavedView]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const [source,setSource]=useState(null),[sourceError,setSourceError]=useState('');
  const [sourceLoading,setSourceLoading]=useState(false);
  const [selectedImage,setSelectedImage]=useState(0);
  const [creditsOpen,setCreditsOpen]=useState(false);
  const sourceRequest=useRef(null);
  const briefRef=useRef(null),resultRef=useRef(null),outputRef=useRef(null),uploadRef=useRef(null),creditCloseRef=useRef(null);
  const result=results[tool],preset=STUDIO_PRESETS[fields.preset],resultPreset=STUDIO_PRESETS[result?.fields.preset||fields.preset];
  const outputFields=result?.fields||fields;
  const isInsightBrief=tool==='ideas'&&['competitor-brief','inspiration-brief'].includes(result?.kind);
  const briefSource=result?.kind==='inspiration-brief'?'Steal This':'Competitor Insights';
  const caption=resultPreset.captions[result?.selected||0];
  const text=result?.edits?.[result.selected]??(tool==='captions'?captionText(caption,outputFields.language):tool==='ideas'?resultPreset.ideas.map(([title,format,body])=>`${title} (${format})\n${body}`).join('\n\n'):'');
  const visual=tool==='images';
  const canvas=studioCanvas(fields);
  const canHandoff=!mobileWeb&&tool==='captions'&&!!result;
  const visibleSavedItems=saved.items.filter(item=>isAvailableTool(item.tool));
  const imageVariantArts=[preset.art,STUDIO_PRESETS[fields.preset==='sunset'?'kitchen':'sunset'].art];
  const creditLabel=aiCredits.unlimited?'Unlimited':`${Number(aiCredits.remaining||0).toLocaleString()} left`;
  const usageLabel=aiCredits.unlimited?`${Number(aiCredits.used||0).toLocaleString()} used · Unlimited left`:`${Number(aiCredits.used||0).toLocaleString()} used · ${Number(aiCredits.remaining||0).toLocaleString()} left`;
  const usagePercent=aiCredits.unlimited?0:(aiCredits.limit?Math.max(0,Math.min(100,(Number(aiCredits.used||0)/Number(aiCredits.limit))*100)):0);
  useEffect(()=>()=>{if(source?.url)URL.revokeObjectURL(source.url);},[source]);
  useEffect(()=>()=>sourceRequest.current?.abort(),[]);
  useEffect(()=>{if(outputRef.current)outputRef.current.scrollTop=0;},[tool,savedView]);
  useEffect(()=>{if(!creditsOpen)return;creditCloseRef.current?.focus();const close=event=>{if(event.key==='Escape')setCreditsOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[creditsOpen]);
  useEffect(()=>{if(!initialSavedId)return;const library=readStudioSaved(),item=library.items.find(savedItem=>savedItem.id===initialSavedId);if(item&&isAvailableTool(item.tool))openSaved(item);else setError(item?'That saved tool is no longer part of AI Studio.':'This saved brief could not be found. Check Saved items.');onInitialSavedOpened();},[initialSavedId]);
  useEffect(()=>{const refresh=()=>setSaved(readStudioSaved());const sync=e=>{if(e.key===null||e.key==='tw_studio_saved_design_v1:preview-marina')refresh();};window.addEventListener('focus',refresh);window.addEventListener('storage',sync);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('storage',sync);};},[]);

  function update(key,value){setFields(current=>({...current,[key]:value,...(key==='ratio'&&value==='original'?{imageFit:'contain'}:{}),...(key==='ratio'&&value!=='custom'?resetInvalidCustomSize(current):{}),...(key==='imageMode'&&value==='generate'&&current.ratio==='original'?{ratio:'1:1'}:{})}));if(isInsightBrief)setResults(current=>({...current,ideas:{...current.ideas,fields:{...current.ideas.fields,[key]:value}}}));setError('');setNotice('');}
  function chooseTool(next){sourceRequest.current?.abort();setSourceLoading(false);if(next!=='images')setFields(current=>({...current,...resetInvalidCustomSize(current),ratio:STUDIO_FORMATS.some(item=>item.id===current.ratio)?current.ratio:'1:1'}));setTool(next);setSavedView(false);setNotice('');setError('');}
  function choosePreset(key){const next=STUDIO_PRESETS[key];setFields(current=>({...current,preset:key,topic:next.topic,headline:next.headline,subline:next.subline}));setNotice(`${next.label} sample brief loaded.`);setError('');briefRef.current?.focus({preventScroll:true});}
  function preview(event){
    event.preventDefault();setNotice('');setError('');
    if(!aiCredits.unlimited&&Number(aiCredits.remaining||0)<=0){setError('You are out of AI credits. Choose a top-up to keep creating.');setCreditsOpen(true);return;}
    if(visual&&(sourceLoading||!canvas)){setError(sourceLoading?'Wait for the image dimensions to finish loading.':'Enter a valid canvas width and height.');return;}
    if(!(tool==='images'?fields.prompt:fields.topic).trim()){setError(tool==='images'?'Describe the image you want to explore.':'Add a brief or choose a sample below.');briefRef.current?.focus();return;}
    if(tool==='images'&&fields.imageMode==='edit'&&!source){setSourceError('Choose an image before previewing the edit layout.');uploadRef.current?.focus();return;}
    setResults(current=>({...current,[tool]:defaultResult(fields)}));setSelectedImage(0);
    setNotice(tool==='images'?'Image layout preview updated. No image was generated or edited.':'Sample results are ready. These examples use the selected sample brief, not live AI generation.');
    requestAnimationFrame(()=>resultRef.current?.focus());
  }
  function editText(value){setResults(current=>({...current,[tool]:{...current[tool],edits:{...current[tool].edits,[current[tool].selected]:value}}}));setNotice('');}
  async function copyText(value=text){setError('');try{if(!navigator.clipboard?.writeText)throw Error('Unavailable');await navigator.clipboard.writeText(value);setNotice('Copied to clipboard.');}catch(_){setError('Clipboard access is unavailable. Select the result text and copy it manually.');}}
  function save(){
    if(visual&&(sourceLoading||!canvas)){setError(sourceLoading?'Wait for the image dimensions to finish loading.':'Enter a valid canvas width and height.');return;}
    if(tool==='images'&&!fields.prompt.trim()){setError('Describe the image before saving.');briefRef.current?.focus();return;}
    if(!visual&&!text.trim()){setError('Add some result text before saving.');return;}
    const itemFields=visual?fields:outputFields;
    const response=saveStudioItem({tool,fields:itemFields,text:visual?'':text,...(isInsightBrief?{kind:result.kind,sourceId:result.sourceId}:{}),title:(isInsightBrief?result.title:tool==='images'?fields.prompt:`${STUDIO_PRESETS[itemFields.preset].label} / ${toolName(tool)}`).slice(0,90)});
    if(!response.ok){setError(response.error);return;}
    setSaved({items:response.items,error:''});setError('');setNotice(visual?'Image saved to your Studio library.':'Saved in this browser. Find it in Saved items.');
  }
  function openSaved(item){sourceRequest.current?.abort();setSourceLoading(false);setSource(null);setSourceError('');setFields({...STUDIO_FORMAT_DEFAULTS,...item.fields});setTool(item.tool);setResults(current=>({...current,[item.tool]:{fields:{...item.fields},selected:0,edits:{0:item.text},kind:item.kind,sourceId:item.sourceId,title:item.title}}));setSavedView(false);setNotice(['competitor-brief','inspiration-brief'].includes(item.kind)?`Brief from ${item.kind==='inspiration-brief'?'Steal This':'Competitor Insights'} opened. Edit it here and save a new version. This is not generated content.`:'Saved item opened. Changes will save as a new version. Image files are not stored; choose a source image again to edit it.');setError('');}
  function handoff(){if(mobileWeb||!canPublishOnWeb())return;const response=stageStudioCaption(text);if(!response.ok){setError(response.error);return;}onOpenPublisher();}
  function useIdea(idea){setFields(current=>({...current,topic:`${idea[0]}. ${idea[2]}`,preset:outputFields.preset}));setTool('captions');setSavedView(false);setNotice('Idea added to the caption brief. Preview a sample or write your own version.');requestAnimationFrame(()=>briefRef.current?.focus({preventScroll:true}));}
  async function upload(file){
    if(!file)return;
    sourceRequest.current?.abort();const controller=new AbortController();sourceRequest.current=controller;setSourceLoading(true);setSourceError('');setNotice('');
    try{const next=await readStudioImage(file,controller.signal);if(controller.signal.aborted){URL.revokeObjectURL(next.url);return;}setSource(next);setFields(current=>({...current,...resetInvalidCustomSize(current),originalWidth:next.width,originalHeight:next.height,ratio:'original',imageFit:'contain'}));setNotice(`Image detected: ${dimensionLabel(next)}. Original size selected.`);}
    catch(error){if(!controller.signal.aborted&&error.name!=='AbortError')setSourceError(error.message);}
    finally{if(sourceRequest.current===controller)setSourceLoading(false);}
  }
  function removeSource(){sourceRequest.current?.abort();setSourceLoading(false);setSource(null);setSourceError('');setFields(current=>({...current,originalWidth:0,originalHeight:0,ratio:current.ratio==='original'?'1:1':current.ratio}));setNotice('Source image removed from this preview.');}

  return <main className="tw-studio-experience" data-studio-theme={dark?'dark':'light'}>
    <div className="st-preview-line"><span>Design preview · Sample outputs · No credits used</span><button type="button" className="st-icon" aria-label={dark?'Use light Studio theme':'Use dark Studio theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div>
    <header className="st-heading"><div className="st-heading-copy"><span className="st-kicker"><img src="/logo-transparent.png" alt="" width="22" height="22"/>Marina Social Club / Creative workspace</span><h1>AI Studio.<br/><em>Make the idea visible.</em></h1><p>Move from a clear brief to words, visual direction and a post you can keep shaping.</p><button type="button" className="st-button st-saved-button" aria-pressed={savedView} onClick={()=>{setSavedView(!savedView);setError('');setNotice('');}}><Bookmark size={17} aria-hidden="true"/>Saved items <span>{visibleSavedItems.length}</span></button></div><div className="st-heading-scene" aria-hidden="true"><div className="st-scene-orbit"/><figure className="st-scene-art"><Artwork post={{art:preset.art}}/></figure><div className="st-scene-copy"><span>{toolName(tool)} / {fields.language==='both'?'EN + AR':fields.language.toUpperCase()}</span><strong>{caption.en.split('.').slice(0,2).join('.')}.</strong><small>Shape it in your voice →</small></div><div className="st-scene-language"><span>EN</span><span lang="ar">ع</span></div></div></header>
    <nav className="st-tools" aria-label="Studio tools">{TOOLS.map(([id,label,Icon])=><button type="button" key={id} aria-pressed={!savedView&&tool===id} onClick={()=>chooseTool(id)}><Icon size={18} aria-hidden="true"/>{label}</button>)}</nav>
    {(error||saved.error)&&<p className="st-error" role="alert">{error||saved.error}</p>}
    <p className="st-feedback" role="status" aria-live="polite">{notice&&<><Check size={16} aria-hidden="true"/>{notice}</>}</p>
    {savedView?<section className="st-saved" aria-labelledby="st-saved-title"><div className="st-section-title"><h2 id="st-saved-title">Your saved work.</h2><button type="button" className="st-text-button" onClick={()=>setSavedView(false)}><ArrowLeft size={17} aria-hidden="true"/>Back to Studio</button></div><p>Kept in this browser for the sample workspace. Nothing is sent or published.</p>{visibleSavedItems.length?<ul>{visibleSavedItems.map(item=><li key={item.id}><button type="button" onClick={()=>openSaved(item)}><span className="st-saved-type">{toolName(item.tool)}</span><strong>{item.title}</strong><span>{item.tool==='images'?'Saved image':'Saved text'} · Open<ArrowUpRight size={17} aria-hidden="true"/></span></button></li>)}</ul>:<div className="st-empty-library"><Bookmark size={30} aria-hidden="true"/><h3>Keep the good ones.</h3><p>Save a caption, an idea set or an image here to return to it later.</p><button type="button" className="st-button" onClick={()=>setSavedView(false)}>Explore Studio<ArrowRight size={17} aria-hidden="true"/></button></div>}</section>:<div className="st-workbench" data-tool={tool}>
      <section className="st-brief" aria-labelledby="st-brief-title"><span className="st-eyebrow">Your brief</span><h2 id="st-brief-title">{TOOLS.find(([id])=>id===tool)[3]}</h2><p className="st-intro">{tool==='images'?'Set the visual direction before moving into production.':'A few clear details make a stronger starting point.'}</p>
        <form onSubmit={preview}>
          {tool==='images'?<>
            <fieldset className="st-choice-group"><legend>Image task</legend><div>{[['generate','Create image'],['edit','Edit image']].map(([id,label])=><button key={id} type="button" aria-pressed={fields.imageMode===id} onClick={()=>{sourceRequest.current?.abort();setSourceLoading(false);update('imageMode',id);setSourceError('');}}>{label}</button>)}</div></fieldset>
            {fields.imageMode==='edit'&&<div className="st-upload" aria-busy={sourceLoading}><label htmlFor="st-source"><Upload size={18} aria-hidden="true"/>Choose a source image</label><input ref={uploadRef} id="st-source" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}} aria-invalid={!!sourceError} aria-describedby={sourceError?'st-source-help st-source-error':'st-source-help'}/><small id="st-source-help">JPG, PNG or WebP, up to 10 MB. Dimensions are detected on this device.</small>{sourceLoading&&<p className="st-result-note" role="status">Reading image dimensions…</p>}{sourceError&&<p id="st-source-error" role="alert" className="st-error">{sourceError}</p>}{source&&<span className="st-source-name"><span>{source.name}<small>{dimensionLabel(source)}</small></span><button type="button" className="st-icon" aria-label="Remove source image from preview" onClick={removeSource}><X size={16}/></button></span>}</div>}
            <Field label={fields.imageMode==='edit'?'What would you change?':'Describe your image'}><textarea ref={briefRef} rows={4} maxLength={2000} value={fields.prompt} onChange={e=>update('prompt',e.target.value)} placeholder="Describe the scene, lighting and mood."/></Field>
          </>:<Field label="What are we creating?"><textarea ref={briefRef} rows={4} maxLength={2000} value={fields.topic} onChange={e=>update('topic',e.target.value)} placeholder="Describe the product, occasion or idea."/></Field>}
          {!visual&&<div className="st-field-grid"><Field label="Platform"><select value={fields.platform} onChange={e=>update('platform',e.target.value)}>{PLATFORMS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>{tool==='captions'&&<><Field label="Tone"><select value={fields.tone} onChange={e=>update('tone',e.target.value)}>{['Warm','Direct','Story-led'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Language"><select value={fields.language} onChange={e=>update('language',e.target.value)}><option value="both">English + Arabic</option><option value="en">English</option><option value="ar">Arabic</option></select></Field>{fields.language!=='en'&&<Field label="Arabic dialect"><select value={fields.dialect} onChange={e=>update('dialect',e.target.value)}>{[['msa','Standard Arabic'],['gulf','Gulf'],['saudi','Saudi'],['egyptian','Egyptian'],['levantine','Levantine']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>}</>}</div>}
          {visual&&<FormatControls fields={fields} update={update} source={source} loading={sourceLoading} images={tool==='images'}/>}
          <div className="st-form-end"><button type="submit" className="st-button st-primary" disabled={visual&&(sourceLoading||!canvas)}>{tool==='images'?(fields.imageMode==='edit'?'Apply edit':'Generate 2 images'):`Preview ${tool==='ideas'?'ideas':tool}`}<ArrowRight size={18} aria-hidden="true"/></button><p>{tool==='images'?'Each request creates two options and uses one shared AI credit.':'Sample preview only · Live generation uses one shared AI credit.'}</p></div>
        </form>
        {!visual&&<div className="st-starters"><span className="st-eyebrow">Start with an example</span>{Object.entries(STUDIO_PRESETS).map(([key,item])=><button type="button" key={key} onClick={()=>choosePreset(key)}>{item.label}<ArrowUpRight size={16} aria-hidden="true"/></button>)}</div>}
      </section>
      <section ref={outputRef} className="st-output" data-tool={tool} data-visual={visual?'true':undefined} aria-labelledby="st-output-title"><header className="st-output-head"><div><span className="st-eyebrow">{tool==='images'?'Visual direction':isInsightBrief?`From ${briefSource}`:'The working draft'}</span><h2 id="st-output-title" ref={resultRef} tabIndex={-1}>{tool==='images'?'Choose your image.':isInsightBrief?'Shape your next experiment.':result?'Room to refine.':'See where it could go.'}</h2></div><div className="st-output-badges"><span className="st-output-note">{visual?canvas?.ratio||'Custom size':'Preview only'}</span><button type="button" className="st-usage-meter" onClick={()=>setCreditsOpen(true)} aria-label={`${usageLabel} in the shared AI credit wallet. Open credit options.`}><span className="st-usage-copy"><Sparkles size={13} aria-hidden="true"/><span><strong>{usageLabel}</strong><small>Shared across Captions, Post ideas and Images</small></span></span><span className="st-usage-track" aria-hidden="true"><span style={{width:`${usagePercent}%`}}/></span></button></div></header>
        {visual&&!canvas?<p className="st-result-note">Choose a valid size to see the canvas.</p>:tool==='images'?<>{fields.imageMode==='generate'?<div className="st-image-options" role="group" aria-label="Generated image options">{imageVariantArts.map((art,index)=><button type="button" key={`${art}-${index}`} className="st-image-option" aria-pressed={selectedImage===index} onClick={()=>setSelectedImage(index)}><span className="st-image-option-label"><span>Option {index+1}</span>{selectedImage===index&&<Check size={14} aria-hidden="true"/>}</span><span className="st-canvas st-image-canvas" style={{aspectRatio:canvas.aspect,'--st-canvas-ratio':canvas.width/canvas.height}}><span className="st-sample-image"><span style={{width:`${Math.min(canvas.width,canvas.height)/canvas.width*100}%`,aspectRatio:'1 / 1'}}><Artwork post={{art}}/></span></span></span></button>)}</div>:<div className="st-canvas st-image-canvas st-single-image" style={{aspectRatio:canvas.aspect,'--st-canvas-ratio':canvas.width/canvas.height,maxWidth:Math.min(520,600*canvas.width/canvas.height)}}>{source?<img src={source.url} style={{objectFit:fields.imageFit}} alt={fields.imageFit==='cover'?'Source image with a centered crop preview; original file unchanged':'Original source, unchanged in this preview'}/>:<div className="st-image-empty"><Image size={28} aria-hidden="true"/><span>Choose an image to preview it at this size.</span></div>}</div>}<p className="st-canvas-caption"><strong>{fields.imageMode==='generate'?`Option ${selectedImage+1} selected`:canvas.label}</strong><span>{dimensionLabel(canvas)}</span></p><p className="st-result-note">{fields.imageMode==='edit'?(source?(fields.imageFit==='cover'?'Centered crop preview. The original file is unchanged.':'Original image, unchanged. The canvas matches your selected size.'):'Choose a source image to preview the edit.'):'Two options are created per request. One request uses one shared AI credit.'}</p><div className="st-image-actions"><button type="button" className="st-text-button" onClick={save} disabled={!!saved.error||sourceLoading||!canvas}><Bookmark size={17} aria-hidden="true"/>Save image</button><button type="button" className="st-text-button" onClick={()=>setCreditsOpen(true)}><CreditCard size={17} aria-hidden="true"/>Buy AI credits</button></div></>:!result?<div className="st-awaiting"><div className="st-awaiting-art"><Artwork post={{art:preset.art}}/></div><h3>One brief. A few new angles.</h3><p>Preview the sample to explore a carousel, a reel and a story direction.</p></div>:<>
          <p className="st-sample-label">{isInsightBrief?`Creative brief · ${briefSource}`:`Sample content · ${resultPreset.label}`} · {PLATFORMS.find(([id])=>id===outputFields.platform)[1]}</p>
          {tool==='captions'&&<><div className="st-variants" role="group" aria-label="Caption variations">{resultPreset.captions.map((item,index)=><button key={item.label} type="button" aria-pressed={result.selected===index} onClick={()=>{setResults(current=>({...current,captions:{...current.captions,selected:index}}));setNotice('');}}>{item.label}</button>)}</div><label className="st-proof-label" htmlFor="st-edit-result">Edit caption</label><textarea id="st-edit-result" className="st-proof" rows={outputFields.language==='both'?9:6} maxLength={12000} value={text} dir={outputFields.language==='ar'?'rtl':'auto'} lang={outputFields.language==='ar'?'ar':undefined} onChange={e=>editText(e.target.value)}/><div className="st-proof-meta"><span>{text.length.toLocaleString()} characters</span><span>{outputFields.language==='both'?'English + Arabic':outputFields.language==='ar'?'Arabic':'English'}</span></div>{outputFields.language!=='en'&&<p className="st-result-note">Arabic samples use Standard Arabic. Other dialects need live generation.</p>}</>}
          {isInsightBrief&&<><label className="st-proof-label" htmlFor="st-insight-brief">Edit creative brief</label><textarea id="st-insight-brief" className="st-proof" rows={16} maxLength={12000} value={text} onChange={e=>editText(e.target.value)}/><p className="st-result-note">Original direction with its sample evidence and limits. This is a brief, not a finished caption.</p></>}
          {tool==='ideas'&&!isInsightBrief&&<ol className="st-ideas">{resultPreset.ideas.map((idea,index)=><li key={idea[0]}><span className="st-idea-format">{idea[1]}</span><h3>{idea[0]}</h3><p>{idea[2]}</p><button type="button" className="st-text-button" onClick={()=>useIdea(idea)}>Build a caption<ArrowRight size={16} aria-hidden="true"/></button></li>)}</ol>}
          <div className="st-result-actions"><button type="button" className="st-text-button" onClick={()=>copyText()}><Copy size={17} aria-hidden="true"/>Copy {isInsightBrief?'brief':tool==='ideas'?'ideas':'text'}</button><button type="button" className="st-text-button" onClick={save} disabled={!!saved.error}><Bookmark size={17} aria-hidden="true"/>Save {isInsightBrief?'brief':tool==='ideas'?'ideas':'caption'}</button>{canHandoff&&<button type="button" className="st-button" data-publishing-action="true" onClick={handoff}>Open in Publisher<ArrowUpRight size={17} aria-hidden="true"/></button>}</div>
          {isInsightBrief&&<p className="st-result-note">This brief uses illustrative {result.kind==='inspiration-brief'?'inspiration':'competitor evidence'}. No live AI response has been generated.</p>}
        </>}
      </section>
    </div>}
    {creditsOpen&&createPortal(<div className="st-credit-overlay" data-studio-theme={dark?'dark':'light'} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setCreditsOpen(false);}}><section className="st-credit-dialog" role="dialog" aria-modal="true" aria-labelledby="st-credit-title"><header><div><span className="st-eyebrow">Shared AI allowance</span><h2 id="st-credit-title">{!aiCredits.unlimited&&Number(aiCredits.remaining||0)<=0?'You are out of AI credits.':'Add credits to your AI wallet.'}</h2></div><button ref={creditCloseRef} type="button" className="st-icon" aria-label="Close AI credit options" onClick={()=>setCreditsOpen(false)}><X size={18}/></button></header><div className="st-credit-current"><Sparkles size={18} aria-hidden="true"/><span><strong>{creditLabel}</strong><small>{aiCredits.planName||aiCredits.packName||'Essential'} plan · {aiCredits.allowanceLabel||'No AI credits included'}</small></span></div><p className="st-credit-explainer">One balance works everywhere in AI Studio: Captions, Post ideas and Images each use one credit per request.</p><div className="st-credit-columns"><div><h3>Monthly AI credit packs</h3><p>Shared across all three tools and refreshed monthly.</p>{AI_CREDIT_PACKS.map(([name,count,price])=><button type="button" key={name} onClick={()=>{setCreditsOpen(false);onBuyAiCredits();}}><span><strong>{name}</strong><small>{count} AI credits / month</small></span><b>{price}<small>/ month</small></b></button>)}</div><div><h3>One-time top-ups</h3><p>Available when the shared balance runs out. They never expire.</p>{AI_CREDIT_TOPUPS.map(([count,price])=><button type="button" key={count} onClick={()=>{setCreditsOpen(false);onBuyAiCredits();}}><span><strong>+{count} AI credits</strong><small>Works across all Studio tools</small></span><b>{price}</b></button>)}</div></div><button type="button" className="st-button st-primary st-credit-manage" onClick={()=>{setCreditsOpen(false);onBuyAiCredits();}}>Manage plans and AI credits<ArrowRight size={17} aria-hidden="true"/></button></section></div>,document.body)}
  </main>;
}
