import {cloneElement,useEffect,useId,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,ChevronLeft,ChevronRight,Copy,Heart,Info,MessageCircle,Moon,Plus,Search,Sun,Trash2,X} from 'lucide-react';
import {FaInstagram,FaTiktok} from 'react-icons/fa';
import {COMPETITOR_KEY,COMPETITOR_MONTHS,COMPETITOR_NETWORKS,compactCount,monthName,competitorRows,competitorPosts,ideaText,readCompetitorSaved,addPreviewCompetitor,removePreviewCompetitor,saveCompetitorIdea} from './competitorPreviewModel';
import './competitor-experience.css';
import './competitor-findings.css';
import CompetitorFindings from './CompetitorFindings';

const ICONS={ig:FaInstagram,tt:FaTiktok};
function Field({label,children,hint}){const id=useId();return <div className="cp-field"><label htmlFor={id}>{label}</label>{cloneElement(children,{id,'aria-describedby':[hint?`${id}-hint`:null,children.props['aria-describedby']].filter(Boolean).join(' ')||undefined})}{hint&&<small id={`${id}-hint`}>{hint}</small>}</div>;}
function PostArt({post}){return <div className={`cp-art cp-look-${post.look}`} role="img" aria-label={`Fictional sample artwork: ${post.title}`}><span>{post.accountName}</span><svg viewBox="0 0 400 400" aria-hidden="true"><path d="M-60 300Q50 180 160 300T380 300T600 300 M-60 328Q50 208 160 328T380 328T600 328 M-60 356Q50 236 160 356T380 356T600 356"/>{post.look==='olive'?<path d="M270 90Q370 130 270 240Q190 130 270 90 M270 120V285"/>:post.look==='afterglow'?<circle cx="300" cy="185" r="65"/>:null}</svg><strong>{post.title}</strong><small>Fictional creative / Design example</small></div>;}
function Avatar({account}){return <span className={`cp-avatar cp-look-${account.look||'custom'}`} aria-hidden="true">{account.initials||account.name.slice(0,1).toUpperCase()}</span>;}
export default function CompetitorExperience({dark=false,setDark=()=>{},onOpenStudio=()=>{}}){
  const [saved,setSaved]=useState(()=>readCompetitorSaved()),[platform,setPlatform]=useState('ig'),[month,setMonth]=useState('2026-08'),[selected,setSelected]=useState('coast');
  const [tab,setTab]=useState('overview'),[sort,setSort]=useState('rate'),[format,setFormat]=useState('All'),[post,setPost]=useState(null);
  const [adding,setAdding]=useState(false),[name,setName]=useState(''),[handle,setHandle]=useState(''),[formError,setFormError]=useState(null);
  const [notice,setNotice]=useState(''),[error,setError]=useState(''),[removeId,setRemoveId]=useState(null),[copyFallback,setCopyFallback]=useState('');
  const [returnInsight,setReturnInsight]=useState('');
  const handleRef=useRef(null),nameRef=useRef(null),addRef=useRef(null),detailRef=useRef(null),contentRef=useRef(null),copyRef=useRef(null);
  const rows=competitorRows(platform,month,saved.accounts),account=rows.find(a=>a.id===selected)||rows[1],own=rows[0],metrics=account.metrics;
  const sorted=[...rows].sort((a,b)=>{if(!a.metrics)return b.metrics?1:a.name.localeCompare(b.name);if(!b.metrics)return -1;return b.metrics[sort]-a.metrics[sort];});
  const maxRate=Math.ceil(Math.max(...rows.filter(a=>a.metrics).map(a=>a.metrics.rate))),posts=competitorPosts(account,platform,month),visiblePosts=posts.filter(item=>format==='All'||item.format===format);
  const monthIndex=COMPETITOR_MONTHS.indexOf(month),Platform=ICONS[platform];
  useEffect(()=>{const refresh=()=>setSaved(readCompetitorSaved());const change=e=>{if(e.key===COMPETITOR_KEY||e.key===null)refresh();};window.addEventListener('focus',refresh);window.addEventListener('storage',change);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('storage',change);};},[]);
  function accept(result,message){if(!result.ok){setError(result.error);return false;}setSaved({accounts:result.accounts,ideas:result.ideas,error:''});setError('');setNotice(message);return true;}
  function changePlatform(next){setPlatform(next);setSelected('coast');setFormat('All');setPost(null);setRemoveId(null);setAdding(false);setFormError(null);setNotice('');setError('');setCopyFallback('');}
  function changeMonth(next){if(!COMPETITOR_MONTHS.includes(next))return;setMonth(next);setPost(null);setNotice('');setError('');setCopyFallback('');}
  function chooseAccount(id){setSelected(id);setPost(null);setRemoveId(null);setFormat('All');setError('');setCopyFallback('');}
  function chooseTab(next){setTab(next);setPost(null);setCopyFallback('');setError('');setReturnInsight('');}
  function add(event){event.preventDefault();const result=addPreviewCompetitor({name,handle},platform);if(!result.ok){setFormError(result);(result.field==='name'?nameRef:handleRef).current?.focus();return;}accept(result,'Added to this browser preview. No account data has been retrieved.');setSelected(result.account.id);setTab('overview');setAdding(false);setName('');setHandle('');setFormError(null);requestAnimationFrame(()=>detailRef.current?.focus({preventScroll:true}));}
  function saveIdea(item){const result=saveCompetitorIdea(item);accept(result,result.alreadySaved?'This idea is already saved.':'Idea saved in this browser. Find it in Saved ideas.');}
  async function copy(item){const value=ideaText(item);try{await navigator.clipboard.writeText(value);setNotice('Creative brief copied. Use your own wording and original media.');setError('');setCopyFallback('');}catch(_){setCopyFallback(value);setError('Clipboard access is unavailable. Select the brief below and copy it manually.');requestAnimationFrame(()=>copyRef.current?.focus());}}
  function openPost(item){setReturnInsight('');setPost(item);requestAnimationFrame(()=>detailRef.current?.focus());}
  function openEvidence(item,insightId){setSelected(item.accountId);setTab('content');setPost(item);setReturnInsight(insightId);requestAnimationFrame(()=>detailRef.current?.focus());}
  function backFromPost(){setPost(null);if(returnInsight){setTab('overview');setReturnInsight('');requestAnimationFrame(()=>document.getElementById('ci-title')?.focus());}else requestAnimationFrame(()=>contentRef.current?.focus());}
  function openContent(){setTab('content');setPost(null);setFormat('All');requestAnimationFrame(()=>contentRef.current?.focus());}
  function isSaved(item){return saved.ideas.some(idea=>idea.id===item.id);}
  const saveButton=item=><button className="cp-button" disabled={!!saved.error||isSaved(item)} onClick={()=>saveIdea(item)}>{isSaved(item)?<Check size={16} aria-hidden="true"/>:<Bookmark size={16} aria-hidden="true"/>}{isSaved(item)?'Idea saved':'Save idea'}</button>;

  return <main className="tw-competitor-experience" data-competitor-theme={dark?'dark':'light'}>
    <div className="cp-preview-line"><span>Design preview · Fictional accounts and metrics · No live scans</span><button className="cp-icon" aria-label={dark?'Use light competitor theme':'Use dark competitor theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div>
    <header className="cp-heading"><div><span className="cp-kicker"><img src="/logo-transparent.png" alt="" width="22" height="22"/>Marina Social Club / Market perspective</span><h1>Competitor Insights</h1><p>Find an opportunity. Turn it into your next original idea.</p></div><button ref={addRef} className="cp-button cp-primary" aria-expanded={adding} aria-controls="cp-add" onClick={()=>{setAdding(!adding);setFormError(null);if(!adding)requestAnimationFrame(()=>handleRef.current?.focus());}}><Plus size={18} aria-hidden="true"/>Add competitor</button></header>
    <div className="cp-toolbar"><div className="cp-platforms" role="group" aria-label="Comparison platform">{Object.entries(COMPETITOR_NETWORKS).map(([id,label])=>{const Icon=ICONS[id];return <button key={id} aria-pressed={platform===id} onClick={()=>changePlatform(id)}><Icon size={17} aria-hidden="true"/>{label}</button>;})}</div><div className="cp-month"><button className="cp-icon" aria-label="Previous sample month" disabled={monthIndex===0} onClick={()=>changeMonth(COMPETITOR_MONTHS[monthIndex-1])}><ChevronLeft size={17}/></button><Field label="Sample month"><select value={month} onChange={e=>changeMonth(e.target.value)}>{COMPETITOR_MONTHS.map(key=><option key={key} value={key}>{monthName(key)}</option>)}</select></Field><button className="cp-icon" aria-label="Next sample month" disabled={monthIndex===COMPETITOR_MONTHS.length-1} onClick={()=>changeMonth(COMPETITOR_MONTHS[monthIndex+1])}><ChevronRight size={17}/></button></div></div>
    {adding&&<section id="cp-add" className="cp-add"><div className="cp-section-head"><div><span className="cp-eyebrow">Your comparison list</span><h2>Add {platform==='ig'?'an Instagram':'a TikTok'} account.</h2></div><button className="cp-icon" aria-label="Close add competitor" onClick={()=>{setAdding(false);addRef.current?.focus();}}><X size={18}/></button></div><p>Keep a handle for later. Live lookup is not connected, so we will not invent stats or an analysis for it.</p><form onSubmit={add} noValidate><Field label="Competitor handle" hint="A handle, not a profile link."><input ref={handleRef} value={handle} maxLength={80} placeholder="@competitor" autoCapitalize="none" autoCorrect="off" spellCheck="false" aria-invalid={formError?.field==='handle'||undefined} aria-describedby={formError?.field==='handle'?'cp-add-error':undefined} onChange={e=>{setHandle(e.target.value);setFormError(null);}}/></Field><Field label="Account name (optional)"><input ref={nameRef} maxLength={60} value={name} placeholder="A name you recognise" aria-invalid={formError?.field==='name'||undefined} aria-describedby={formError?.field==='name'?'cp-add-error':undefined} onChange={e=>{setName(e.target.value);setFormError(null);}}/></Field><button className="cp-button cp-primary" disabled={!!saved.error}>Add to preview</button></form>{formError&&<p id="cp-add-error" className="cp-error" role="alert">{formError.error}</p>}</section>}
    <nav className="cp-tabs" aria-label="Competitor workspace">{[['overview','Overview'],['content','Content examples'],['saved','Saved ideas']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>chooseTab(id)}>{label}{id==='saved'&&<span>{saved.ideas.length}</span>}</button>)}</nav>
    <div className="cp-notice" role="status">{notice}</div>{(error||saved.error)&&<p className="cp-error" role="alert">{error||saved.error}</p>}
    {copyFallback&&<Field label="Brief to copy"><textarea ref={copyRef} readOnly rows={7} value={copyFallback}/></Field>}

    <div className="ci-view" hidden={tab!=='overview'}><CompetitorFindings platform={platform} month={month} onOpenPost={openEvidence} onOpenStudio={onOpenStudio} PostArt={PostArt} onCompare={()=>document.getElementById('cp-benchmark-title')?.focus()}/></div>
    {tab==='overview'&&<>
      <section className="cp-benchmark" aria-labelledby="cp-benchmark-title"><div className="cp-section-head"><div><span className="cp-eyebrow">The same platform. A fairer view.</span><h2 id="cp-benchmark-title" tabIndex={-1}>How the accounts compare.</h2><p>Choose an account to see its approach and content.</p></div><Field label="Sort accounts by"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="rate">Interaction rate</option><option value="followers">Followers</option><option value="posts">Posts this month</option></select></Field></div>
      <div className="cp-comparison-head" aria-hidden="true"><span>Account</span><span>Followers</span><span>Posts</span><span>Interaction rate <small>0 to {maxRate}%</small></span><span/></div>
      <ul className="cp-comparisons" aria-label="Account comparisons">{sorted.map(item=><li key={item.id}><button className={`cp-comparison cp-look-${item.look||'custom'}`} aria-pressed={account.id===item.id} onClick={()=>chooseAccount(item.id)} aria-label={`${item.name}${item.own?', your account':''}. ${item.metrics?`${item.metrics.followers.toLocaleString('en-GB')} followers, ${item.metrics.posts} posts, ${item.metrics.rate.toFixed(1)}% interaction rate.`:'Not analysed.'} View account.`}><span className="cp-account"><Avatar account={item}/><span><strong>{item.name}</strong><small>{item.own?'Your account · Sample data':`@${item.handle}`}</small></span></span><span className="cp-number"><small>Followers</small>{item.metrics?compactCount(item.metrics.followers):'No data'}</span><span className="cp-number"><small>Posts</small>{item.metrics?item.metrics.posts:'No data'}</span><span className="cp-rate"><small>Interaction rate</small>{item.metrics?<><strong>{item.metrics.rate.toFixed(1)}%</strong><span className="cp-track" aria-hidden="true"><span style={{width:`${item.metrics.rate/maxRate*100}%`}}/></span></>:<span>Not analysed</span>}</span><span className="cp-row-indicator">{account.id===item.id?<Check size={18} aria-hidden="true"/>:<ArrowRight size={18} aria-hidden="true"/>}</span></button></li>)}</ul>
      <details className="cp-method"><summary><Info size={14} aria-hidden="true"/>What do these numbers mean?</summary><p>Every number here is illustrative. Interaction rate = average likes and comments per post ÷ followers × 100. It excludes reach, views, saves and shares. Compare within the same platform and month. The content below shows selected examples, not the full dataset.</p></details></section>
      <section className="cp-account-detail" aria-label="Selected account"><div className="cp-profile"><div className="cp-profile-name"><Avatar account={account}/><div><span className="cp-eyebrow">{metrics?'Sample account / Closer look':'Custom account / Preview only'}</span><h2 ref={detailRef} tabIndex={-1}>{account.name}</h2><p><Platform size={15} aria-hidden="true"/>@{account.handle}</p></div></div>{metrics?<><p className="cp-comparison-summary">{account.own?'Your baseline for this comparison.':Math.abs(metrics.rate-own.metrics.rate)<.05?'About the same interaction rate as Marina in this sample.':`${Math.abs(metrics.rate-own.metrics.rate).toFixed(1)} percentage points ${metrics.rate>own.metrics.rate?'above':'below'} Marina in this sample.`}</p><div className="cp-mini-stats"><div><strong>{metrics.average.toLocaleString('en-GB')}</strong><span>Avg. interactions / post</span></div><div><strong>{metrics.posts}</strong><span>Posts in {monthName(month).split(' ')[0]}</span></div></div><button className="cp-button" onClick={openContent}>Explore content<ArrowRight size={17} aria-hidden="true"/></button></>:<><p>No analysis yet. This handle is saved only in your browser preview. Live metrics and content have not been retrieved.</p>{removeId===account.id?<div className="cp-remove-confirm" role="region" aria-label="Remove custom competitor"><p>Remove @{account.handle} from this preview list?</p><div className="cp-actions"><button className="cp-button" onClick={()=>setRemoveId(null)}>Keep account</button><button className="cp-text-button" onClick={()=>{if(accept(removePreviewCompetitor(account.id),'Custom account removed from this preview list.')){setSelected('coast');setRemoveId(null);}}}>Remove account</button></div></div>:<button className="cp-text-button" disabled={!!saved.error} onClick={()=>setRemoveId(account.id)}><Trash2 size={15} aria-hidden="true"/>Remove from preview</button>}</>}</div>
      {metrics&&<div className="cp-perspective"><span className="cp-eyebrow">A direction, not a diagnosis</span><h3>What to take from it.</h3><div className="cp-insight"><span>{account.own?'Your approach':'Their approach'}</span><p>{account.approach}</p></div><div className="cp-insight"><span>An angle for Marina</span><p>{account.angle}</p></div><div className="cp-mix"><span className="cp-eyebrow">Example content mix</span><div className="cp-mix-bar" aria-hidden="true">{metrics.mix.map((count,index)=>count?<span key={index} className={`cp-mix-${index}`} style={{width:`${count/metrics.posts*100}%`}}/>:null)}</div><ul>{metrics.mix.map((count,index)=>count?<li key={index}><span className={`cp-mix-dot cp-mix-${index}`} aria-hidden="true"/>{platform==='tt'?'Videos':['Reels','Carousels','Photos'][index]}<strong>{count}</strong><small>{Math.round(count/metrics.posts*100)}%</small></li>:null)}</ul></div></div>}</section>
      {metrics&&<section className="cp-content-preview"><div className="cp-section-head"><div><span className="cp-eyebrow">From the example feed</span><h2>Look beyond the numbers.</h2></div><button className="cp-text-button" onClick={openContent}>See all examples<ArrowRight size={16} aria-hidden="true"/></button></div><div className="cp-post-grid">{posts.map(item=><button key={item.id} className="cp-post-link" onClick={()=>{setTab('content');openPost(item);}}><PostArt post={item}/><span className="cp-post-meta">{item.format}<span>{item.day} {monthName(month).split(' ')[0]}</span></span><strong>{item.title}</strong><span className="cp-post-open">View example<ArrowRight size={16} aria-hidden="true"/></span></button>)}</div></section>}
    </>}

    {tab==='content'&&<section className="cp-content"><div className="cp-section-head"><div><span className="cp-eyebrow">Selected fictional posts</span><h2 ref={contentRef} tabIndex={-1}>The content behind the comparison.</h2><p>Explore the approach, then make something of your own.</p></div><Field label="Content account"><select value={account.id} onChange={e=>chooseAccount(e.target.value)}>{rows.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>
      {post?<><button className="cp-text-button cp-back" onClick={backFromPost}><ArrowLeft size={16} aria-hidden="true"/>{returnInsight?'Back to insight':'Back to content'}</button><article className="cp-post-detail"><PostArt post={post}/><div><span className="cp-eyebrow">{post.accountName} / {post.format} / {post.day} {monthName(month)}</span><h3 ref={detailRef} tabIndex={-1}>{post.title}</h3><p className="cp-caption">{post.caption}</p><div className="cp-post-stats"><span><Heart size={16} aria-hidden="true"/>{post.likes.toLocaleString('en-GB')} likes</span><span><MessageCircle size={16} aria-hidden="true"/>{post.comments} comments</span></div><div className="cp-idea"><span className="cp-eyebrow">An original direction for Marina</span><p>{post.brief}</p></div><div className="cp-actions">{saveButton(post)}<button className="cp-text-button" onClick={()=>copy(post)}><Copy size={16} aria-hidden="true"/>Copy creative brief</button></div><p className="cp-help">Fictional artwork and metrics. This is not a copied social post or a live AI analysis.</p></div></article></>:<><div className="cp-content-filter" role="group" aria-label="Content format">{(platform==='tt'?['All','Video']:['All','Reel','Carousel','Photo']).map(value=><button key={value} aria-pressed={format===value} onClick={()=>setFormat(value)}>{value==='All'?'All formats':value}</button>)}<span>{visiblePosts.length} examples · {monthName(month)}</span></div>{!visiblePosts.length?<div className="cp-empty"><Search size={28} aria-hidden="true"/><h3>No content retrieved.</h3><p>This custom handle has not been analysed. Choose a sample account to explore the design.</p><button className="cp-button" onClick={()=>chooseAccount('coast')}>View a sample account</button></div>:<div className="cp-post-grid">{visiblePosts.map(item=><article className="cp-post" key={item.id}><button className="cp-post-link" onClick={()=>openPost(item)}><PostArt post={item}/><span className="cp-post-meta">{item.format}<span>{item.day} {monthName(month).split(' ')[0]}</span></span><strong>{item.title}</strong><span className="cp-post-open">View example<ArrowRight size={16} aria-hidden="true"/></span></button><div className="cp-post-stats"><span aria-label={`${item.likes.toLocaleString('en-GB')} likes`}><Heart size={14} aria-hidden="true"/>{item.likes.toLocaleString('en-GB')}</span><span aria-label={`${item.comments} comments`}><MessageCircle size={14} aria-hidden="true"/>{item.comments}</span></div>{saveButton(item)}</article>)}</div>}</>}
    </section>}

    {tab==='saved'&&<section className="cp-saved"><div className="cp-section-head"><div><span className="cp-eyebrow">Keep the idea. Make it yours.</span><h2>Your saved directions.</h2><p>Saved in this browser, across both platforms and sample months.</p></div></div>{!saved.ideas.length?<div className="cp-empty"><Bookmark size={28} aria-hidden="true"/><h3>Something worth trying?</h3><p>Save an idea from a content example. Its creative brief will be waiting here.</p><button className="cp-button" onClick={()=>chooseTab('content')}>Explore content examples<ArrowRight size={16} aria-hidden="true"/></button></div>:<ul>{saved.ideas.map(idea=><li key={idea.id}><span className="cp-eyebrow">{COMPETITOR_NETWORKS[idea.platform]} / {idea.accountName} / {monthName(idea.month)}</span><h3>{idea.title}</h3><p>{idea.brief}</p><button className="cp-text-button" onClick={()=>copy(idea)}><Copy size={16} aria-hidden="true"/>Copy creative brief</button></li>)}</ul>}</section>}
    <footer className="cp-footer"><img src="/logo-transparent.png" alt="" width="18" height="18"/><span>Perspective for your next original idea.</span><span>No accounts scanned. No posts published.</span></footer>
  </main>;
}
