// Fictional comparison data for the isolated design preview. No live lookups.
export const COMPETITOR_KEY='tw_competitor_design_v1:preview-marina';
export const COMPETITOR_MONTHS=['2026-07','2026-08'];
export const COMPETITOR_NETWORKS={ig:'Instagram',tt:'TikTok'};
export const SAMPLE_COMPETITORS=[
  {id:'marina',name:'Marina Social Club',handle:'marinasocialclub',initials:'M',look:'marina',own:true,approach:'A warm welcome, sharing dishes and a recognisable waterfront setting.',angle:'Put the people behind the welcome into the story, not only the finished plate.'},
  {id:'coast',name:'Coast & Co.',handle:'coast.demo',initials:'C',look:'coast',approach:'A consistent coastal look and short videos that start with the setting.',angle:'Show a complete afternoon at Marina, from the first coffee to the last conversation.'},
  {id:'olive',name:'Olive House',handle:'olive.demo',initials:'O',look:'olive',approach:'Ingredient-led storytelling, close-up details and useful menu carousels.',angle:'Introduce one kitchen team member through the story of a favourite dish.'},
  {id:'afterglow',name:'Afterglow Table',handle:'afterglow.demo',initials:'A',look:'afterglow',approach:'Atmospheric evening content with a clear reason to visit.',angle:'Give the evening a human perspective: friends arriving, a shared dish and a final view.'},
];
// Followers, posts, average likes, average comments, format counts (video/carousel/photo).
const METRICS={
  ig:{'2026-08':[[18400,18,394,48,[8,6,4]],[24800,24,796,47,[12,8,4]],[32600,20,702,80,[4,12,4]],[12800,12,388,34,[8,2,2]]],
      '2026-07':[[17700,16,355,36,[6,6,4]],[23700,22,699,40,[10,8,4]],[31900,21,656,61,[5,12,4]],[12100,14,323,28,[8,3,3]]]},
  tt:{'2026-08':[[8900,16,700,42,[16,0,0]],[17600,20,1480,110,[20,0,0]],[13200,14,880,73,[14,0,0]],[22000,22,1836,144,[22,0,0]]],
      '2026-07':[[8200,14,630,37,[14,0,0]],[16200,18,1340,98,[18,0,0]],[12500,12,810,65,[12,0,0]],[20700,20,1720,122,[20,0,0]]]},
};
export const compactCount=n=>n>=1000?`${(n/1000).toFixed(1)}k`:String(n);
export const monthName=value=>new Date(Number(value.slice(0,4)),Number(value.slice(5))-1,1).toLocaleDateString('en-GB',{month:'long',year:'numeric'});
export function competitorMetrics(id,platform,month){const index=SAMPLE_COMPETITORS.findIndex(account=>account.id===id),values=METRICS[platform]?.[month]?.[index];if(!values)return null;const [followers,posts,likes,comments,mix]=values;return {followers,posts,likes,comments,mix,average:likes+comments,rate:(likes+comments)/followers*100};}
export function competitorRows(platform,month,custom=[]){return [...SAMPLE_COMPETITORS,...custom.filter(account=>account.platform===platform)].map(account=>({...account,metrics:competitorMetrics(account.id,platform,month)}));}
const POST_COPY={
  marina:[['A little more weekend.','Follow an unhurried afternoon from the first coffee to the last conversation.','Film a slow afternoon at Marina in three moments. Keep the opening specific and end with a gentle invitation.'],['Made for sharing.','A closer look at the dishes made for the middle of the table.','Create an original carousel pairing three sharing dishes with three reasons to gather at Marina.'],['Meet you by the water.','A place to settle in, with the view doing the rest.','Photograph a favourite waterfront seat and write a short invitation in Marina\'s own voice.']],
  coast:[['Stay for the sea.','A short journey from the terrace to a table with a view.','Film a guest\'s afternoon at Marina: arrival, a sharing plate and a quiet moment by the water. Use original footage and copy.'],['Your afternoon, sorted.','A simple sequence of food, setting and a reason to visit.','Build a Marina carousel around an unhurried afternoon. Give each frame one useful detail, then invite guests to book.'],['One more conversation.','A table that invites guests to stay a little longer.','Create an original image of a shared table at Marina. Let the caption focus on the company, not just the food.']],
  olive:[['From the first ingredient.','A kitchen story told through the hands behind a dish.','Introduce a Marina team member through three stages of preparing their favourite dish. Let them narrate one personal detail.'],['A closer look at the menu.','A useful, easy-to-follow guide to seasonal dishes.','Create a Marina menu carousel with one dish per frame, a flavour note and a serving suggestion.'],['Made with a little care.','A single ingredient becomes the focus of the frame.','Photograph an ingredient from Marina\'s kitchen and tell its story in your own words.']],
  afterglow:[['An evening worth keeping.','The light changes, but the story stays with the guests.','Film three moments of an evening at Marina. Include a human moment so the story is about more than the sunset.'],['Make a night of it.','An invitation built around a whole evening, not one dish.','Plan a Marina evening carousel that moves from arrival to a shared meal to the waterfront view.'],['Last light. Good company.','One atmospheric frame with a simple invitation.','Capture original golden-hour photography at Marina. Pair it with a specific, understated invitation.']],
};
export function competitorPosts(account,platform,month){const metrics=competitorMetrics(account.id,platform,month);if(!metrics)return [];return POST_COPY[account.id].map(([title,caption,brief],index)=>({id:`${platform}:${month}:${account.id}:${index}`,accountId:account.id,accountName:account.name,look:account.look,title,caption,brief,platform,month,format:platform==='tt'?'Video':['Reel','Carousel','Photo'][index],day:[24,17,8][index],likes:Math.round(metrics.likes*[1.65,1.25,.92][index]),comments:Math.round(metrics.comments*[1.5,1.3,.9][index])}));}
export function ideaText(idea){return `${idea.title}\n\nCreative brief for Marina Social Club\n${idea.brief}\n\nInspired by a fictional ${COMPETITOR_NETWORKS[idea.platform]} example from ${idea.accountName}, ${monthName(idea.month)}. Create original content; this is not a live competitor analysis.`;}
const text=(value,max)=>typeof value==='string'&&value.length>0&&value.length<=max;
const isPlatform=platform=>Object.hasOwn(COMPETITOR_NETWORKS,platform);
export function readCompetitorSaved(store){try{const raw=(store||window.localStorage).getItem(COMPETITOR_KEY),data=raw?JSON.parse(raw):{accounts:[],ideas:[]};
  if(!data||!Array.isArray(data.accounts)||!Array.isArray(data.ideas)||data.accounts.length>10||data.ideas.length>100||!data.accounts.every(account=>account&&text(account.id,100)&&account.id.startsWith('competitor-')&&text(account.name,60)&&!!account.name.trim()&&text(account.handle,40)&&/^[a-z0-9_.]{1,40}$/.test(account.handle)&&isPlatform(account.platform))||!data.ideas.every(idea=>idea&&text(idea.id,120)&&text(idea.title,120)&&text(idea.brief,3000)&&text(idea.accountName,60)&&isPlatform(idea.platform)&&COMPETITOR_MONTHS.includes(idea.month)&&Number.isFinite(idea.savedAt))||new Set(data.accounts.map(a=>a.id)).size!==data.accounts.length||new Set(data.accounts.map(a=>`${a.platform}:${a.handle}`)).size!==data.accounts.length||new Set(data.ideas.map(idea=>idea.id)).size!==data.ideas.length)throw Error('Invalid saved data');
  return {...data,error:''};
}catch(_){return {accounts:[],ideas:[],error:'Saved competitors and ideas could not be read. Saving is paused to protect them. You can still explore the examples.'};}}
function writeSaved(data,store){try{(store||window.localStorage).setItem(COMPETITOR_KEY,JSON.stringify({accounts:data.accounts,ideas:data.ideas}));return {ok:true,...data,error:''};}catch(_){return {ok:false,error:'Not saved. Browser storage is full or unavailable. Your current page is still available.'};}}
export function addPreviewCompetitor(input,platform,store){const current=readCompetitorSaved(store);if(current.error)return {ok:false,error:current.error};const handle=String(input.handle||'').trim().replace(/^@/,'').toLowerCase(),name=String(input.name||'').trim()||handle;
  if(!isPlatform(platform)||!/^[a-z0-9_.]{1,40}$/.test(handle))return {ok:false,field:'handle',error:'Enter a handle using letters, numbers, dots or underscores, up to 40 characters. Do not enter a link.'};
  if(name.length>60)return {ok:false,field:'name',error:'Keep the account name to 60 characters or fewer.'};
  if(SAMPLE_COMPETITORS.some(a=>a.handle===handle)||current.accounts.some(a=>a.handle===handle&&a.platform===platform))return {ok:false,field:'handle',error:'This account is already in your comparison.'};
  if(current.accounts.length>=10)return {ok:false,error:'This preview holds up to 10 custom competitors. Remove one before adding another.'};
  const account={id:`competitor-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name,handle,platform};const result=writeSaved({...current,accounts:[...current.accounts,account]},store);return {...result,account:result.ok?account:undefined};
}
export function removePreviewCompetitor(id,store){const current=readCompetitorSaved(store);if(current.error)return {ok:false,error:current.error};if(!current.accounts.some(a=>a.id===id))return {ok:false,error:'This custom account is no longer in the comparison.'};return writeSaved({...current,accounts:current.accounts.filter(a=>a.id!==id)},store);}
export function saveCompetitorIdea(post,store){const current=readCompetitorSaved(store);if(current.error)return {ok:false,error:current.error};const account=SAMPLE_COMPETITORS.find(a=>a.id===post?.accountId),canonical=account&&competitorPosts(account,post.platform,post.month).find(p=>p.id===post.id);if(!canonical)return {ok:false,error:'This example could not be saved. Choose a post from the sample content.'};if(current.ideas.some(idea=>idea.id===canonical.id))return {ok:true,...current,alreadySaved:true};if(current.ideas.length>=100)return {ok:false,error:'This preview has reached 100 saved ideas. Copy the brief to keep another.'};const {id,title,brief,accountName,platform,month}=canonical;return writeSaved({...current,ideas:[{id,title,brief,accountName,platform,month,savedAt:Date.now()},...current.ideas]},store);}
