import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowRight,Check,ChevronDown,ChevronUp,FileText,Info} from 'lucide-react';
import {competitorInsights,insightBrief,saveInsightBrief} from './competitorInsightsModel';
import {monthName,COMPETITOR_NETWORKS} from './competitorPreviewModel';

export default function CompetitorFindings({platform,month,onOpenPost,onOpenStudio,PostArt,returnId,onCompare}){
  const insights=competitorInsights(platform,month);
  const [expanded,setExpanded]=useState(returnId||''),[showEvidence,setShowEvidence]=useState({}),[drafts,setDrafts]=useState({}),[editing,setEditing]=useState('');
  const [savedIds,setSavedIds]=useState({}),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const briefRef=useRef(null);
  useEffect(()=>{setNotice('');setError('');},[platform,month]);
  function createBrief(insight){setEditing(insight.id);setDrafts(current=>({...current,[insight.id]:current[insight.id]??insightBrief(insight)}));setError('');requestAnimationFrame(()=>briefRef.current?.focus());}
  function save(insight){const response=saveInsightBrief(insight,drafts[insight.id]??insightBrief(insight));if(!response.ok){setError(response.error);requestAnimationFrame(()=>briefRef.current?.focus());return;}setSavedIds(current=>({...current,[insight.id]:response.id}));setError('');setNotice('Brief saved in AI Studio, in this browser. Nothing has been generated or published.');}
  return <section className="ci-findings" aria-labelledby="ci-title">
    <div className="ci-heading"><div><span className="cp-eyebrow">From comparison to a content decision</span><h2 id="ci-title" tabIndex={-1}>What’s worth testing this month.</h2><p>{insights.length} example findings · {COMPETITOR_NETWORKS[platform]} · {monthName(month)}</p></div><button className="cp-text-button" onClick={onCompare}>Compare accounts<ArrowDown size={16} aria-hidden="true"/></button></div>
    <p className="ci-disclosure"><Info size={15} aria-hidden="true"/>Illustrative findings, not live analysis. Open the evidence before choosing a test.</p>
    <div className="ci-list">{insights.map(insight=>{
      const open=expanded===insight.id,id=`ci-${insight.key}`,max=Math.max(...insight.values.map(v=>v.value));
      return <article className="ci-finding" key={insight.id}>
        <h3><button className="ci-summary" aria-expanded={open} aria-controls={id} onClick={()=>{setExpanded(open?'':insight.id);setError('');}}><span className="ci-thumb" aria-hidden="true"><PostArt post={insight.evidence[0]}/></span><span className="ci-summary-copy"><span className="cp-eyebrow">{insight.category}</span><strong>{insight.title}</strong><span>{insight.summary}</span></span><span className="ci-open-label">{open?'Close':'Explore'}{open?<ChevronUp size={18} aria-hidden="true"/>:<ChevronDown size={18} aria-hidden="true"/>}</span></button></h3>
        {open&&<div id={id} className="ci-detail"><div className="ci-observation"><span className="cp-eyebrow">What the sample shows</span><h4>{insight.measure}</h4><div className="ci-bars">{insight.values.map((value,index)=><div key={value.label}><span>{value.label}</span><strong>{value.display}</strong><span className="ci-track" aria-hidden="true"><span data-baseline={index===1?'true':undefined} style={{width:`${value.value/max*100}%`}}/></span></div>)}</div><p className="ci-limit">{insight.limitation}</p><button className="cp-text-button" aria-expanded={!!showEvidence[insight.id]} aria-controls={`${id}-evidence`} onClick={()=>setShowEvidence(current=>({...current,[insight.id]:!current[insight.id]}))}>{showEvidence[insight.id]?'Hide supporting examples':`View ${insight.evidence.length} supporting examples`}<ChevronDown size={16} aria-hidden="true"/></button></div>
          <div className="ci-experiment"><span className="cp-eyebrow">An original test for Marina</span><p>{insight.experiment}</p><h4>How to judge it</h4><p className="ci-success">{insight.success}</p><button className="cp-button cp-primary" onClick={()=>createBrief(insight)}><FileText size={17} aria-hidden="true"/>{editing===insight.id?'Edit brief':'Create a brief'}</button></div>
          {showEvidence[insight.id]&&<div id={`${id}-evidence`} className="ci-evidence"><h4>Supporting examples</h4><p>Selected fictional posts. Click any example to inspect its creative and metrics.</p><ul>{insight.evidence.map(post=><li key={post.id}><button onClick={()=>onOpenPost(post,insight.id)}><span className="ci-evidence-art" aria-hidden="true"><PostArt post={post}/></span><span><strong>{post.title}</strong><small>{post.accountName} · {post.format} · {post.day} {monthName(post.month)}</small></span><span className="ci-evidence-count"><strong>{post.comments}</strong><small>comments</small></span><ArrowRight size={17} aria-hidden="true"/></button></li>)}</ul></div>}
          {editing===insight.id&&<div className="ci-brief"><div><h4>A brief you can make your own.</h4><p>Keep your original direction. The sample evidence and its limitations are attached when you save.</p></div><label htmlFor={`${id}-brief`}>Creative brief</label><textarea ref={briefRef} id={`${id}-brief`} rows={9} maxLength={6000} aria-invalid={!!error&&!drafts[insight.id]?.trim()||undefined} aria-describedby={error?`${id}-error`:undefined} value={drafts[insight.id]??''} onChange={event=>{setDrafts(current=>({...current,[insight.id]:event.target.value}));setSavedIds(current=>({...current,[insight.id]:null}));setNotice('');setError('');}}/>{error&&<p id={`${id}-error`} className="cp-error" role="alert">{error}</p>}<div className="cp-actions"><button className="cp-button cp-primary" disabled={!!savedIds[insight.id]} onClick={()=>save(insight)}>{savedIds[insight.id]?<Check size={17} aria-hidden="true"/>:<FileText size={17} aria-hidden="true"/>}{savedIds[insight.id]?'Brief saved':'Save brief to AI Studio'}</button>{savedIds[insight.id]&&<button className="cp-text-button" onClick={()=>onOpenStudio(savedIds[insight.id])}>Open brief in AI Studio<ArrowRight size={17} aria-hidden="true"/></button>}</div><p className="ci-help">Saved as a creative brief, not a scheduled post. Available in AI Studio’s Saved items.</p></div>}
        </div>}
      </article>;
    })}</div>
    <p className="ci-notice" role="status">{notice}</p>
  </section>;
}
