import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Check,Download,Edit3,Film,Folder,Heart,Image as ImageIcon,Megaphone,Search,Sparkles,Upload,X} from 'lucide-react';
import {Artwork} from './CalendarExperience';
import {MEDIA_KINDS,MEDIA_PLATFORMS,MEDIA_STATUS_LABELS,SAMPLE_MEDIA_ASSETS,assetById,filterMediaAssets,readMediaFavorites,readMediaRoute,toggleMediaFavorite} from './mediaPreviewModel';
import './media-experience.css';

const PLATFORM_NAMES={ig:'Instagram',fb:'Facebook',li:'LinkedIn',tt:'TikTok'};
const STATUS_COPY={ready:'Prepared for your next post.',campaign:'Already connected to an active campaign.',needsAlt:'Add descriptive text before publishing.',unused:'Not used in a post yet.'};

function AssetVisual({asset,large=false}){
  if(asset.localUrl&&asset.kind==='video')return <video src={asset.localUrl} controls={large} muted={!large} playsInline aria-label={asset.alt}/>;
  if(asset.localUrl)return <img src={asset.localUrl} alt={asset.alt}/>;
  return <><Artwork post={{art:asset.art}} compact={!large}/>{asset.kind==='video'&&<span className="ml-play" aria-hidden="true"><Film size={large?24:17}/></span>}</>;
}

export default function MediaExperience({dark=false,setDark=()=>{},mobileWeb=false,onOpenPublisher=()=>{},onOpenStudio=()=>{},liveAssets=null,clientName='',onUpload=null}){
  const initial=readMediaRoute(window.location.search),stored=readMediaFavorites();
  const [route,setRoute]=useState(initial),[favorites,setFavorites]=useState(stored.items),[assets,setAssets]=useState(liveAssets||SAMPLE_MEDIA_ASSETS),[selectedId,setSelectedId]=useState(initial.asset||SAMPLE_MEDIA_ASSETS[0].id),[checked,setChecked]=useState([]),[dropActive,setDropActive]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(stored.error);
  const inputRef=useRef(null),localUrls=useRef([]),dragDepth=useRef(0);
  const shown=useMemo(()=>filterMediaAssets(assets,{...route,favorites}),[assets,route,favorites]);
  const checkedSet=useMemo(()=>new Set(checked),[checked]);
  const attentionCount=useMemo(()=>filterMediaAssets(assets,{...route,view:'attention',favorites}).length,[assets,route.kind,route.platform,route.query,favorites]);
  const visibleReadyCount=useMemo(()=>shown.filter(asset=>asset.status==='ready').length,[shown]);
  const visibleLabel=route.kind==='photo'?'photos':route.kind==='design'?'designs':route.kind==='video'?'videos':'assets';
  const selected=assetById(selectedId,assets)||shown[0]||assets[0];
  const featured=shown.length?[selected,...shown.filter(asset=>asset.id!==selected.id)].slice(0,3):[];
  useEffect(()=>()=>localUrls.current.forEach(url=>URL.revokeObjectURL?.(url)),[]);
  useEffect(()=>{if(liveAssets)setAssets(liveAssets);},[liveAssets]);
  useEffect(()=>{if(shown.length&&!shown.some(asset=>asset.id===selectedId))setSelectedId(shown[0].id);},[shown,selectedId]);
  useEffect(()=>{const onPop=()=>{const next=readMediaRoute(window.location.search);setRoute(next);if(next.asset)setSelectedId(next.asset);};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
  function update(next){const value={...route,...next};setRoute(value);const url=new URL(window.location.href);value.kind==='all'?url.searchParams.delete('mediaType'):url.searchParams.set('mediaType',value.kind);value.platform==='all'?url.searchParams.delete('mediaPlatform'):url.searchParams.set('mediaPlatform',value.platform);value.view==='all'?url.searchParams.delete('mediaView'):url.searchParams.set('mediaView',value.view);value.query?url.searchParams.set('mediaSearch',value.query):url.searchParams.delete('mediaSearch');window.history.replaceState({},'',url);setNotice('');}
  function choose(id){setSelectedId(id);const url=new URL(window.location.href);url.searchParams.set('asset',id);window.history.replaceState({},'',url);}
  function toggleChecked(id){setChecked(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);setNotice('');}
  function favorite(){const response=toggleMediaFavorite(selected.id,favorites);setFavorites(response.items);setError(response.error);if(response.ok)setNotice(response.items.includes(selected.id)?'Saved to favorites.':'Removed from favorites.');}
  function upload(fileList){const files=Array.from(fileList||[]).slice(0,12),valid=files.filter(file=>/^(image|video)\//.test(file.type)&&file.size<=20*1024*1024);if(!valid.length){setError('Choose images or videos up to 20 MB each.');return;}const added=valid.map((file,index)=>{const localUrl=typeof URL.createObjectURL==='function'?URL.createObjectURL(file):'';if(localUrl)localUrls.current.push(localUrl);return {id:`local-${Date.now()}-${index}`,title:file.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' '),fileName:file.name,kind:file.type.startsWith('video/')?'video':'photo',platform:'ig',collection:'Added now',width:0,height:0,size:`${Math.max(.1,file.size/1024/1024).toFixed(1)} MB`,added:'Just now',usage:0,status:'needsAlt',shape:file.type.startsWith('video/')?'portrait':'square',alt:`Local preview of ${file.name}`,history:[],localUrl};});setAssets(current=>[...added,...current]);if(onUpload)onUpload(valid);setSelectedId(added[0].id);setError('');setNotice(`${added.length} ${added.length===1?'asset':'assets'} added to this preview. Nothing was uploaded.`);if(inputRef.current)inputRef.current.value='';}
  function runBatch(action){const count=checked.length;if(!count)return;if(action==='move'){setAssets(current=>current.map(asset=>checkedSet.has(asset.id)?{...asset,collection:'Campaign selects'}:asset));setNotice(`${count} ${count===1?'asset':'assets'} moved to Campaign selects in this preview.`);}else if(action==='campaign'){setAssets(current=>current.map(asset=>checkedSet.has(asset.id)?{...asset,status:'campaign'}:asset));setNotice(`${count} ${count===1?'asset':'assets'} added to the Weekend Social campaign in this preview.`);}else if(action==='download')setNotice(`${count} ${count===1?'asset is':'assets are'} ready. Live file downloads are not connected in this preview.`);setChecked([]);}
  function dragEnter(event){event.preventDefault();dragDepth.current+=1;setDropActive(true);}
  function dragLeave(event){event.preventDefault();dragDepth.current=Math.max(0,dragDepth.current-1);if(!dragDepth.current)setDropActive(false);}
  function drop(event){event.preventDefault();dragDepth.current=0;setDropActive(false);upload(event.dataTransfer?.files);}
  function openPublisher(){try{if(selected.localUrl)sessionStorage.setItem('tw_studio_media',selected.localUrl);}catch(_){}onOpenPublisher(selected);}
  function openStudio(){try{sessionStorage.setItem('tw_studio_imgprompt',`Edit ${selected.title} for Marina Social Club. Keep the current visual direction.`);}catch(_){}onOpenStudio(selected);}
  return <main className={`tw-media-library${dropActive?' ml-is-dropping':''}`} data-media-theme={dark?'dark':'light'} onDragEnter={dragEnter} onDragOver={event=>event.preventDefault()} onDragLeave={dragLeave} onDrop={drop}>
    <header className="ml-heading">
      <div className="ml-heading-copy">
        <span className="ml-kicker"><img src="/logo-transparent.png" alt="" width="22" height="22"/>{clientName||'Marina Social Club'} / Media Library</span>
        <h1>Every asset, ready to move.</h1>
        <p>Find approved photos, videos and designs—then send them straight into your next post.</p>
        <div className="ml-facts" aria-live="polite"><span><strong>{shown.length}</strong><small>{visibleLabel} in view</small></span><span><strong>{visibleReadyCount}</strong><small>ready to use</small></span><span className={attentionCount?'ml-fact-attention':''}><strong>{attentionCount}</strong><small>need attention</small></span></div>
        <div className="ml-heading-actions"><button className="ml-button ml-primary" onClick={()=>inputRef.current?.click()}><Upload size={17}/>Upload assets</button><button className="ml-button ml-secondary" onClick={()=>onOpenStudio(selected)}><Sparkles size={17}/>Open AI Studio</button><input ref={inputRef} className="ml-file-input" type="file" multiple accept="image/*,video/*" onChange={event=>upload(event.target.files)}/></div>
      </div>
      <div className="ml-heading-side">
        {!!featured.length&&<><div className="ml-cover-run" aria-label="Featured assets">{featured.map(asset=><button type="button" key={asset.id} aria-label={`Select ${asset.title}`} aria-pressed={selected.id===asset.id} onClick={()=>choose(asset.id)}><span><AssetVisual asset={asset}/></span></button>)}</div><div className="ml-featured-meta"><span>Selected now</span><strong>{selected.title}</strong><small>{MEDIA_STATUS_LABELS[selected.status]||'Review'} · {selected.collection}</small></div></>}
      </div>
    </header>
    <div className="ml-feedback" role="status">{notice}</div>{error&&<p className="ml-error" role="alert">{error}</p>}
    <section className="ml-controls" aria-label="Media filters"><label className="ml-search"><Search size={17} aria-hidden="true"/><span className="sr-only">Search assets</span><input type="search" value={route.query} placeholder="Search assets" onChange={event=>update({query:event.target.value.slice(0,80)})}/>{route.query&&<button aria-label="Clear search" onClick={()=>update({query:''})}><X size={16}/></button>}</label><div className="ml-tabs" aria-label="Asset type">{MEDIA_KINDS.map(([id,label])=><button key={id} aria-pressed={route.kind===id} onClick={()=>update({kind:id})}>{label}</button>)}</div><label className="ml-channel"><span>Channel</span><select value={route.platform} onChange={event=>update({platform:event.target.value})}>{MEDIA_PLATFORMS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></section>
    <button className="ml-drop-band" data-active={dropActive?'true':'false'} onClick={()=>inputRef.current?.click()}><Upload size={18}/><span><strong>{dropActive?'Release to add assets':'Drop assets here'}</strong><small>Images or videos up to 20 MB, or browse files</small></span><span className="ml-drop-browse">Browse</span></button>
    <div className={`ml-workspace${shown.length?'':' ml-workspace-empty'}`}><section className="ml-contact" aria-labelledby="ml-contact-title"><div className="ml-section-heading"><div><span className="ml-eyebrow">Your library</span><h2 id="ml-contact-title">{shown.length} {shown.length===1?'asset':'assets'} in view</h2></div><div className="ml-view-switch"><button aria-pressed={route.view==='all'} onClick={()=>update({view:'all'})}>All assets</button><button aria-pressed={route.view==='favorites'} onClick={()=>update({view:'favorites'})}>Favorites <span>{favorites.length}</span></button><button aria-pressed={route.view==='attention'} onClick={()=>update({view:'attention'})}>Needs attention <span>{attentionCount}</span></button></div></div>{shown.length?<div className="ml-grid">{shown.map(asset=><article key={asset.id} className={`ml-tile ml-${asset.shape}`} data-checked={checkedSet.has(asset.id)?'true':'false'}><button className="ml-tile-open" aria-pressed={selected.id===asset.id} aria-label={`Select ${asset.title}`} onClick={()=>choose(asset.id)}><span className="ml-tile-visual"><AssetVisual asset={asset}/><span className="ml-kind">{asset.kind}</span>{favorites.includes(asset.id)&&<Heart className="ml-favorite-mark" size={17} fill="currentColor" aria-label="Favorite"/>}</span><span className="ml-tile-copy"><strong>{asset.title}</strong><small>{asset.collection} · {asset.added}</small><span className={`ml-status ml-status-${asset.status}`}>{MEDIA_STATUS_LABELS[asset.status]||'Review'}</span></span></button><button className="ml-select-toggle" aria-label={checkedSet.has(asset.id)?`Remove ${asset.title} from selection`:`Add ${asset.title} to selection`} aria-pressed={checkedSet.has(asset.id)} onClick={()=>toggleChecked(asset.id)}>{checkedSet.has(asset.id)?<Check size={16}/>:<span aria-hidden="true"/>}</button></article>)}</div>:<div className="ml-empty"><ImageIcon size={30}/><h3>{route.view==='favorites'?'No favorites match these filters.':route.view==='attention'?'Everything in this view is ready.':'No assets match these filters.'}</h3><p>{route.view==='attention'?'There are no missing details or unused assets here.':'Clear the search or choose a different type or channel.'}</p><button className="ml-text-button" onClick={()=>update({kind:'all',platform:'all',view:'all',query:''})}>Clear filters</button></div>}</section>
      {!!shown.length&&<aside className="ml-inspector" aria-labelledby="ml-selected-title"><div className="ml-inspector-heading"><span className="ml-eyebrow">Selected asset</span>{!selected.localUrl&&<button className="ml-heart" aria-label={favorites.includes(selected.id)?'Remove from favorites':'Add to favorites'} aria-pressed={favorites.includes(selected.id)} onClick={favorite}><Heart size={19} fill={favorites.includes(selected.id)?'currentColor':'none'}/></button>}</div><figure className={`ml-selected-visual ml-${selected.shape}`}><AssetVisual asset={selected} large/></figure><div className="ml-selected-copy"><h2 id="ml-selected-title">{selected.title}</h2><p>{selected.fileName}</p></div><div className={`ml-readiness ml-readiness-${selected.status}`}><span>{MEDIA_STATUS_LABELS[selected.status]||'Review'}</span><p>{STATUS_COPY[selected.status]||'Review this asset before using it.'}</p></div><dl><div><dt>Format</dt><dd>{selected.kind==='video'?'Video':selected.kind==='design'?'Design':'Photo'}</dd></div><div><dt>Dimensions</dt><dd>{selected.width&&selected.height?`${selected.width.toLocaleString()} × ${selected.height.toLocaleString()} px`:'Original size'}</dd></div><div><dt>Channel</dt><dd>{PLATFORM_NAMES[selected.platform]||'All channels'}</dd></div><div><dt>Collection</dt><dd>{selected.collection}</dd></div></dl><section className="ml-usage" aria-label="Recent usage"><div className="ml-usage-title"><span>Recently used in</span><strong>{selected.usage} {selected.usage===1?'post':'posts'}</strong></div>{selected.history?.length?<ol>{selected.history.slice(0,2).map((item,index)=><li key={`${item.title}-${index}`}><span/><div><strong>{item.title}</strong><small>{item.detail}</small></div></li>)}</ol>:<p>This asset has not been used yet. It is ready for a new idea.</p>}</section><div className="ml-inspector-actions">{!mobileWeb&&<button className="ml-button ml-primary" onClick={openPublisher}><ArrowUpRight size={17}/>Use in Publisher</button>}<button className="ml-button" onClick={openStudio}><Edit3 size={17}/>Edit in AI Studio</button></div><p className="ml-local-note">Sample asset library. Uploading here adds files to this browser preview only.</p></aside>}
    </div>
    {checked.length>0&&<aside className="ml-batch-dock" aria-label="Selected asset actions"><div className="ml-batch-count"><strong>{checked.length}</strong><span>{checked.length===1?'asset selected':'assets selected'}</span></div><div className="ml-batch-actions"><button onClick={()=>runBatch('campaign')}><Megaphone size={16}/>Add to campaign</button><button onClick={()=>runBatch('move')}><Folder size={16}/>Move to collection</button><button onClick={()=>runBatch('download')}><Download size={16}/>Download</button></div><button className="ml-batch-clear" aria-label="Clear selection" onClick={()=>setChecked([])}><X size={18}/></button></aside>}
    <footer className="ml-footer"><span>Find it. Shape it. Publish it.</span><span>Local preview · No storage changes</span></footer>
  </main>;
}
