export const PROPOSAL_STORAGE_KEY='tw_proposals_design_v1:preview-marina';
export const PROPOSAL_PLATFORMS=[['ig','Instagram'],['tt','TikTok']];
export const PROPOSAL_GOALS=[['bookings','More bookings'],['reach','Local awareness'],['launch','Launch something new'],['community','A stronger community']];
export const PROPOSAL_TYPES=[['meeting','Start with a strategy call'],['proposal','Send a complete proposal'],['audit','Share an audit first']];
export const DEFAULT_PROPOSAL={prospectName:'The Daily Grind',handle:'thedailygrind.bh',platform:'ig',sector:'hospitality',goal:'bookings',pitchType:'proposal',agencyName:'Your agency',contactName:'',packageName:'Social growth plan',price:'450',currency:'BHD',cta:'Book a strategy call',accent:'#B43D31',presentationTheme:'light'};
export const BLANK_PROPOSAL={...DEFAULT_PROPOSAL,prospectName:'',handle:'',price:'',contactName:''};
const GOAL_COPY={
  bookings:{headline:'Turn attention into a reason to visit.',opportunity:'Make every post answer one useful question: why come in, what to try, and how to book.',plan:['Clarify the weekly reasons to visit','Build a recognisable content rhythm','Make booking details easy to find']},
  reach:{headline:'Become easier to notice and remember.',opportunity:'Use a consistent local story so new people understand the brand before they reach the profile.',plan:['Define three repeatable story themes','Strengthen the first second and first line','Review reach and saves every week']},
  launch:{headline:'Give the launch a story people can follow.',opportunity:'Build anticipation before launch day, then turn the strongest questions into useful follow-up content.',plan:['Set the launch narrative and milestones','Create a reveal sequence for each platform','Turn audience questions into the next post']},
  community:{headline:'Give people more ways to join the story.',opportunity:'Move beyond announcements with recurring conversations, guest perspectives, and useful replies.',plan:['Choose one weekly community format','Feature real voices with permission','Use replies to shape the next content cycle']},
};
export function cleanHandle(value=''){return String(value).trim().replace(/^@/,'').toLowerCase();}
export function validateProposal(fields){const errors={};if(!String(fields?.prospectName||'').trim())errors.prospectName='Add the prospect’s business name.';const handle=cleanHandle(fields?.handle);if(!/^[a-z0-9._]{2,40}$/.test(handle))errors.handle='Enter a social handle using letters, numbers, dots or underscores.';if(!PROPOSAL_PLATFORMS.some(([id])=>id===fields?.platform))errors.platform='Choose Instagram or TikTok.';if(!Object.hasOwn(GOAL_COPY,fields?.goal))errors.goal='Choose the outcome this proposal should focus on.';if(!PROPOSAL_TYPES.some(([id])=>id===fields?.pitchType))errors.pitchType='Choose how you want to start the conversation.';if(!String(fields?.agencyName||'').trim())errors.agencyName='Add the agency name shown to the prospect.';if(fields?.pitchType==='proposal'&&(!/^\d+(\.\d{1,2})?$/.test(String(fields.price||''))||Number(fields.price)<=0))errors.price='Enter a valid package price.';if(!/^[A-Z]{3}$/.test(String(fields?.currency||'')))errors.currency='Use a three-letter currency code, such as BHD.';if(!/^#[0-9a-f]{6}$/i.test(String(fields?.accent||'')))errors.accent='Enter a six-digit HEX color.';if(!['light','dark'].includes(fields?.presentationTheme))errors.presentationTheme='Choose a proposal appearance.';for(const key of ['prospectName','handle','agencyName','contactName','packageName','cta'])if(String(fields?.[key]||'').length>120)errors[key]='Keep this field to 120 characters or fewer.';return errors;}
export function proposalDocument(fields){const goal=GOAL_COPY[fields.goal]||GOAL_COPY.bookings;const platform=PROPOSAL_PLATFORMS.find(([id])=>id===fields.platform)?.[1]||'Instagram';return {headline:goal.headline,opportunity:goal.opportunity,plan:goal.plan,platform,intro:`A focused social direction for ${fields.prospectName||'your brand'}, prepared by ${fields.agencyName||'your agency'}.`,offer:fields.pitchType==='meeting'?'A focused strategy call to agree on priorities and the first 30 days.':fields.pitchType==='audit'?'A practical social audit with the clearest opportunities and the first tests to run.':`${fields.packageName||'Social growth plan'} with direction, content planning and a clear review rhythm.`,price:fields.pitchType==='proposal'&&Number(fields.price)>0?`${fields.price} ${fields.currency}`:'',cta:fields.cta||'Start the conversation'};}
export function proposalText(fields){const doc=proposalDocument(fields);return `${fields.prospectName}\n${doc.headline}\n\n${doc.intro}\n\nTHE OPPORTUNITY\n${doc.opportunity}\n\nTHE FIRST 30 DAYS\n${doc.plan.map((item,index)=>`${index+1}. ${item}`).join('\n')}\n\nTHE OFFER\n${doc.offer}${doc.price?`\n${doc.price}`:''}\n\n${doc.cta}\nPrepared by ${fields.agencyName}`;}
const validText=(value,max=120)=>typeof value==='string'&&value.length<=max;
export function validProposalItem(item){return item&&typeof item.id==='string'&&item.id.startsWith('proposal-')&&Number.isFinite(item.savedAt)&&Number.isInteger(item.version)&&item.version>0&&item.fields&&Object.keys(validateProposal(item.fields)).length===0&&['prospectName','handle','platform','sector','goal','pitchType','agencyName','contactName','packageName','price','currency','cta','accent','presentationTheme'].every(key=>validText(item.fields[key]));}
export function readProposals(store){try{const raw=(store||window.localStorage).getItem(PROPOSAL_STORAGE_KEY),items=raw?JSON.parse(raw):[];if(!Array.isArray(items)||items.length>50||!items.every(validProposalItem)||new Set(items.map(item=>item.id)).size!==items.length)throw Error('Invalid proposals');return {items,error:''};}catch(_){return {items:[],error:'Saved proposals could not be read. Saving is paused to protect them. You can still edit and copy this proposal.'};}}
export function saveProposal(fields,sourceId='',store){const errors=validateProposal(fields);if(Object.keys(errors).length)return {ok:false,errors,error:'Complete the highlighted fields before saving.'};const current=readProposals(store);if(current.error)return {ok:false,error:current.error};if(current.items.length>=50)return {ok:false,error:'This preview holds up to 50 saved proposals. Copy your work before adding another.'};const root=sourceId||`proposal-source-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,version=current.items.filter(item=>item.sourceId===root).length+1,item={id:`proposal-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,sourceId:root,version,savedAt:Date.now(),fields:{...fields,handle:cleanHandle(fields.handle),prospectName:fields.prospectName.trim(),agencyName:fields.agencyName.trim()}};try{const items=[item,...current.items];(store||window.localStorage).setItem(PROPOSAL_STORAGE_KEY,JSON.stringify(items));return {ok:true,item,items};}catch(_){return {ok:false,error:'Not saved. Browser storage is full or unavailable. Your proposal is still on this page; copy it to keep it.'};}}
export function readProposalRoute(search=''){const p=new URLSearchParams(search),view=['editor','library','prospect'].includes(p.get('proposalView'))?p.get('proposalView'):'editor',id=/^proposal-[a-z0-9-]{1,80}$/.test(p.get('proposalId')||'')?p.get('proposalId'):'';return {view,id};}
export function readableOnAccent(hex){const safe=/^#[0-9a-f]{6}$/i.test(String(hex||''))?hex:'#B43D31',rgb=safe.replace('#','').match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),lum=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];return (lum+.05)/.05>=4.5?'#171819':'#ffffff';}
