import {cloneElement,useEffect,useId,useRef,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Bookmark,Check,ChevronLeft,ChevronRight,Copy,Film,Mic,Moon,Pause,Play,Plus,RotateCcw,Sun,Trash2} from 'lucide-react';
import {FaInstagram,FaTiktok,FaYoutube} from 'react-icons/fa';
import {canPublishOnWeb} from './workspaceResponsive';
import {stageStudioCaption} from './studioPreviewModel';
import {REEL_STORAGE_KEY,REEL_PLATFORMS,REEL_ART,sampleReel,blankReel,newScene,sceneTimeline,reelDuration,timecode,sceneAt,readReels,saveReel,moveScene,duplicateScene,reelScript} from './reelPreviewModel';
import './reel-studio-experience.css';

const ICONS={ig:FaInstagram,tt:FaTiktok,yt:FaYoutube};
const ART_NAMES={sea:'Waterfront',menu:'The table',kitchen:'The kitchen',sunset:'Golden hour'};
function Field({label,children,hint}) {const id=useId();return <div className="rl-field"><label htmlFor={id}>{label}</label>{cloneElement(children,{id,'aria-describedby':hint?`${id}-hint`:undefined})}{hint&&<small id={`${id}-hint`}>{hint}</small>}</div>;}
function Frame({scene,mini=false,language='en'}) {
  return <div className={`rl-frame rl-art-${scene.art}${mini?' rl-mini':''}`} role={mini?undefined:'img'} aria-hidden={mini?true:undefined} aria-label={mini?undefined:`Storyboard frame: ${scene.onscreen||scene.name}. Sample artwork, not footage.`}>
    <svg className="rl-frame-lines" viewBox="0 0 300 534" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
      {scene.art==='menu'?<><path d="M35 310V535 M22 303V338Q35 363 48 338V303 M67 302V535"/><ellipse cx="241" cy="438" rx="102" ry="137"/><ellipse cx="241" cy="438" rx="78" ry="110"/></>:scene.art==='sunset'?<><circle cx="222" cy="244" r="69"/><path d="M-70 395Q5 340 80 395T230 395T380 395 M-70 418Q5 363 80 418T230 418T380 418 M-70 441Q5 386 80 441T230 441T380 441"/></>:<><path d="M-70 322Q5 267 80 322T230 322T380 322 M-70 347Q5 292 80 347T230 347T380 347 M-70 372Q5 317 80 372T230 372T380 372 M-70 397Q5 342 80 397T230 397T380 397 M-70 422Q5 367 80 422T230 422T380 422"/></>}
    </svg>
    <span className="rl-frame-brand">MARINA<br/>SOCIAL CLUB</span><strong dir={language==='ar'?'rtl':'auto'} data-long={scene.onscreen.length>65?'true':undefined}>{scene.onscreen||'Your words here.'}</strong><span className="rl-frame-bottom">BY THE WATER. IN GOOD COMPANY.</span>
  </div>;
}
export default function ReelStudioExperience({dark=false,setDark=()=>{},mobileWeb=false,onOpenPublisher=()=>{}}) {
  const [project,setProject]=useState(sampleReel),[selected,setSelected]=useState(0),[section,setSection]=useState('storyboard');
  const [saved,setSaved]=useState(readReels),[library,setLibrary]=useState(false),[dirty,setDirty]=useState(false),[pending,setPending]=useState(null);
  const [notice,setNotice]=useState(''),[error,setError]=useState(''),[undo,setUndo]=useState(null);
  const [playing,setPlaying]=useState(false),[position,setPosition]=useState(null);
  const editorRef=useRef(null),replaceRef=useRef(null),copyRef=useRef(null);
  const timeline=sceneTimeline(project.scenes),duration=reelDuration(project.scenes),scene=timeline[Math.min(selected,timeline.length-1)];
  const previewScene=position!==null?sceneAt(project.scenes,position):scene;
  const previewIndex=project.scenes.findIndex(item=>item.id===previewScene.id);
  const PlatformIcon=ICONS[project.platform];
  useEffect(()=>{const refresh=()=>setSaved(readReels());const onStorage=e=>{if(e.key===REEL_STORAGE_KEY||e.key===null)refresh();};window.addEventListener('focus',refresh);window.addEventListener('storage',onStorage);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('storage',onStorage);};},[]);
  useEffect(()=>{if(!dirty)return;const prevent=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
  useEffect(()=>{if(!playing)return;const start=performance.now()-position*1000;const tick=setInterval(()=>{const next=(performance.now()-start)/1000;if(next>=duration){setPosition(0);setPlaying(false);setSelected(0);}else setPosition(next);},100);const hide=()=>{if(document.hidden){setPlaying(false);setSelected(Math.max(0,timeline.findIndex(item=>item.id===sceneAt(project.scenes,(performance.now()-start)/1000).id)));}};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(tick);document.removeEventListener('visibilitychange',hide);};/* Playback restarts only when explicitly requested. */
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[playing,duration]);
  function change(next) {setProject(next);setDirty(true);setPlaying(false);setPosition(null);setNotice('');setError('');setUndo(null);}
  function update(key,value){change({...project,[key]:value});}
  function updateScene(key,value){change({...project,scenes:project.scenes.map(item=>item.id===scene.id?{...item,[key]:value}:item)});}
  function selectScene(index,focus=false){setPlaying(false);setPosition(null);setSelected(index);setSection('storyboard');if(focus)requestAnimationFrame(()=>editorRef.current?.focus({preventScroll:true}));}
  function save(){const response=saveReel(project);if(!response.ok){setError(response.error);return;}setSaved({items:response.items,error:''});setDirty(false);setError('');setNotice('Storyboard saved in this browser. Each save keeps a separate version.');}
  function replace(next){setProject(next);setSelected(0);setSection('storyboard');setLibrary(false);setDirty(false);setPlaying(false);setPosition(null);setUndo(null);setPending(null);setError('');setNotice('Storyboard opened. Edits stay here until you save a version.');}
  function requestReplace(next){if(!dirty){replace(next);return;}setPending(next);requestAnimationFrame(()=>replaceRef.current?.focus());}
  async function copy(){try{await navigator.clipboard.writeText(reelScript(project));setNotice('Full script copied, including scene timings and your caption.');setError('');}catch(_){setSection('script');setError('Clipboard access is unavailable. Select the script below and copy it manually.');requestAnimationFrame(()=>copyRef.current?.focus());}}
  function addScene(){if(project.scenes.length>=12)return;change({...project,scenes:[...project.scenes,newScene()]});selectScene(project.scenes.length,true);}
  function reorder(offset){const next=moveScene(project,scene.id,offset);if(next===project)return;change(next);setSelected(selected+offset);}
  function duplicate(){const next=duplicateScene(project,scene.id);if(next===project)return;change(next);selectScene(selected+1,true);}
  function remove(){if(project.scenes.length===1)return;const previous=project;change({...project,scenes:project.scenes.filter(item=>item.id!==scene.id)});setSelected(Math.max(0,selected-1));setUndo({project:previous,index:selected});setNotice('Scene removed. Undo is available until your next edit.');}
  function handoff(){if(mobileWeb||!canPublishOnWeb())return;if(dirty){const snapshot=saveReel(project);if(!snapshot.ok){setError(snapshot.error);return;}setSaved({items:snapshot.items,error:''});setDirty(false);}const result=stageStudioCaption(project.caption);if(!result.ok){setError(result.error);return;}setPlaying(false);onOpenPublisher();}
  function togglePlayback(){if(playing){setSelected(previewIndex);setPlaying(false);}else{setPosition(position??scene.start);setPlaying(true);}}

  return <main className="tw-reel-experience" data-reel-theme={dark?'dark':'light'}>
    <div className="rl-preview-line"><span>Design preview · Sample storyboard · No credits used</span><button className="rl-icon" aria-label={dark?'Use light Reel Studio theme':'Use dark Reel Studio theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div>
    <header className="rl-heading"><div><span className="rl-kicker"><img src="/logo-transparent.png" alt="" width="22" height="22"/>Marina Social Club / Creative workspace</span><h1>Reel Studio</h1><p>A strong opening. A story worth staying for.</p></div><button className="rl-button" aria-pressed={library} onClick={()=>{setLibrary(!library);setPlaying(false);setPending(null);}}><Bookmark size={17} aria-hidden="true"/>Saved storyboards <span>{saved.items.length}</span></button></header>
    <div className="rl-feedback" role="status">{notice}{undo&&<button className="rl-text-button" onClick={()=>{setProject(undo.project);setSelected(undo.index);setUndo(null);setDirty(true);setNotice('Scene restored.');}}><RotateCcw size={15} aria-hidden="true"/>Undo</button>}</div>
    {(error||saved.error)&&<p className="rl-error" role="alert">{error||saved.error}</p>}
    {pending&&<div className="rl-confirm" role="region" aria-label="Unsaved storyboard"><strong ref={replaceRef} tabIndex={-1}>You have unsaved changes.</strong><p>Save this version first, or open the other storyboard without keeping these edits.</p><div className="rl-actions"><button className="rl-button" onClick={()=>setPending(null)}>Keep editing</button><button className="rl-button" disabled={!!saved.error} onClick={()=>{const result=saveReel(project);if(!result.ok){setError(result.error);return;}setSaved({items:result.items,error:''});replace(pending);}}>Save and open</button><button className="rl-text-button" onClick={()=>replace(pending)}>Discard edits and open</button></div></div>}
    {library?<section className="rl-library"><div className="rl-section-heading"><div><span className="rl-eyebrow">Kept for later</span><h2>Your saved storyboards.</h2></div><button className="rl-text-button" onClick={()=>setLibrary(false)}><ArrowLeft size={16} aria-hidden="true"/>Back to editing</button></div><p>Saved in this browser only. Opening a storyboard does not replace a saved version.</p>{!saved.items.length?<div className="rl-empty"><Film size={30} aria-hidden="true"/><h3>Your next reel starts here.</h3><p>Save your storyboard to keep the scene order, script and timing together.</p><button className="rl-button" onClick={()=>setLibrary(false)}>Continue editing</button></div>:<ul>{saved.items.map(item=><li key={item.id}><button onClick={()=>requestReplace(item.project)}><div className="rl-library-thumb"><Frame scene={item.project.scenes[0]} mini/></div><span><strong>{item.project.title}</strong><small>{REEL_PLATFORMS[item.project.platform]} · {item.project.scenes.length} scenes · {reelDuration(item.project.scenes)}s</small><small>{new Date(item.savedAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</small></span><ArrowRight size={18} aria-hidden="true"/></button></li>)}</ul>}</section>:<>
      <div className="rl-project-bar"><div><span className="rl-eyebrow">Your storyboard</span><h2>{project.title||'Untitled reel'}</h2><span className="rl-project-meta"><Film size={15} aria-hidden="true"/>{project.scenes.length} scenes <span>·</span>{duration} seconds <span>·</span>9:16 <span>·</span>{dirty?'Unsaved changes':'Editable preview'}</span></div><div className="rl-actions"><button className="rl-text-button" onClick={()=>requestReplace(blankReel())}><Plus size={16} aria-hidden="true"/>New</button><button className="rl-button rl-primary" disabled={!!saved.error} onClick={save}><Bookmark size={17} aria-hidden="true"/>Save storyboard</button></div></div>
      <div className="rl-workbench"><div className="rl-desk">
        <nav className="rl-tabs" aria-label="Reel workspace">{[['storyboard','Storyboard'],['brief','Brief'],['caption','Caption & audio'],['script','Full script']].map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>{setSection(id);setPlaying(false);}}>{label}</button>)}</nav>
        {section==='storyboard'&&<section aria-label="Scene editor">
          <div className="rl-storyboard-heading"><p>Choose a scene to shape the story.</p><button className="rl-text-button" onClick={addScene} disabled={project.scenes.length>=12}><Plus size={16} aria-hidden="true"/>Add scene</button></div>
          <ol className="rl-filmstrip">{timeline.map((item,index)=><li key={item.id}><button aria-pressed={selected===index} aria-label={`Scene ${index+1}: ${item.name}, ${item.seconds} seconds`} onClick={()=>selectScene(index)}><div className="rl-scene-art"><Frame scene={item} mini language={project.language}/><span className="rl-scene-number">{String(index+1).padStart(2,'0')}</span>{selected===index&&<span className="rl-scene-check"><Check size={14} aria-hidden="true"/></span>}</div><strong>{item.name}</strong><small>{timecode(item.start)} to {timecode(item.end)}</small></button></li>)}</ol>
          <div className="rl-editor-heading"><div><span className="rl-eyebrow">Scene {selected+1} / {project.scenes.length}</span><h3 ref={editorRef} tabIndex={-1}>{scene.name||'Untitled scene'}</h3></div><div className="rl-scene-actions"><button className="rl-icon" aria-label="Move scene earlier" disabled={selected===0} onClick={()=>reorder(-1)}><ArrowUp size={17}/></button><button className="rl-icon" aria-label="Move scene later" disabled={selected===project.scenes.length-1} onClick={()=>reorder(1)}><ArrowDown size={17}/></button><button className="rl-icon" aria-label="Duplicate scene" disabled={project.scenes.length>=12} onClick={duplicate}><Copy size={17}/></button><button className="rl-icon" aria-label="Remove scene" disabled={project.scenes.length===1} onClick={remove}><Trash2 size={17}/></button></div></div>
          <div className="rl-field-pair"><Field label="Scene name"><input maxLength={60} value={scene.name} onChange={e=>updateScene('name',e.target.value)}/></Field><Field label="Length"><select value={scene.seconds} onChange={e=>updateScene('seconds',Number(e.target.value))}>{Array.from({length:30},(_,i)=><option key={i+1} value={i+1}>{i+1} seconds</option>)}</select></Field></div>
          <Field label="The shot" hint="What should the person filming capture?"><textarea rows={3} maxLength={1000} value={scene.shot} onChange={e=>updateScene('shot',e.target.value)} placeholder="Describe the framing, action and camera movement."/></Field>
          <Field label="On-screen text" hint={`${scene.onscreen.length}/140 characters. Updates the frame preview.`}><textarea rows={2} maxLength={140} dir={project.language==='ar'?'rtl':'auto'} value={scene.onscreen} onChange={e=>updateScene('onscreen',e.target.value)} placeholder="The words your audience will see."/></Field>
          <Field label="Voiceover" hint="Script only. No voice or audio is generated."><textarea rows={3} maxLength={1000} dir={project.language==='ar'?'rtl':'auto'} value={scene.voiceover} onChange={e=>updateScene('voiceover',e.target.value)} placeholder="What should the audience hear?"/></Field>
          <fieldset className="rl-art-options"><legend>Storyboard look <span>Sample artwork, not footage</span></legend><div>{REEL_ART.map(art=><button key={art} aria-pressed={scene.art===art} onClick={()=>updateScene('art',art)}><span className={`rl-swatch rl-art-${art}`} aria-hidden="true"/>{ART_NAMES[art]}</button>)}</div></fieldset>
          <div className="rl-editor-footer"><button className="rl-text-button" disabled={selected===0} onClick={()=>selectScene(selected-1,true)}><ChevronLeft size={16} aria-hidden="true"/>Previous scene</button><button className="rl-text-button" disabled={selected===timeline.length-1} onClick={()=>selectScene(selected+1,true)}>Next scene<ChevronRight size={16} aria-hidden="true"/></button></div>
        </section>}
        {section==='brief'&&<section className="rl-form-section"><span className="rl-eyebrow">Set the direction</span><h3>Give the story a purpose.</h3><Field label="Reel title"><input maxLength={90} value={project.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="What is this reel about?" hint="Your brief stays with the storyboard. Live AI script writing is not connected in this preview."><textarea rows={4} maxLength={1500} value={project.topic} onChange={e=>update('topic',e.target.value)}/></Field><Field label="Destination"><select value={project.platform} onChange={e=>update('platform',e.target.value)}>{Object.entries(REEL_PLATFORMS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="Script language" hint="Sets the writing direction. Existing text is not translated."><select value={project.language} onChange={e=>update('language',e.target.value)}><option value="en">English</option><option value="ar">Arabic</option></select></Field><button className="rl-text-button" onClick={()=>requestReplace(sampleReel())}><RotateCcw size={16} aria-hidden="true"/>Open the sample storyboard</button></section>}
        {section==='caption'&&<section className="rl-form-section"><span className="rl-eyebrow">The finishing touches</span><h3>Carry the story beyond the frame.</h3><Field label="Post caption" hint="Keep the invitation and hashtags together."><textarea rows={7} maxLength={5000} dir={project.language==='ar'?'rtl':'auto'} value={project.caption} onChange={e=>update('caption',e.target.value)}/></Field><Field label="Audio direction" hint="A note for production, not a music track. Check usage rights before adding music."><textarea rows={4} maxLength={1000} value={project.audio} onChange={e=>update('audio',e.target.value)}/></Field>{!mobileWeb&&<><button className="rl-button" disabled={!project.caption.trim()} data-publishing-action="true" onClick={handoff}>Use caption in Publisher<ArrowRight size={17} aria-hidden="true"/></button><p className="rl-help">Moves the caption only. No video is attached and nothing is published.</p></>}</section>}
        {section==='script'&&<section className="rl-form-section"><div className="rl-section-heading"><div><span className="rl-eyebrow">Ready for production</span><h3>The complete shoot plan.</h3></div><button className="rl-text-button" onClick={copy}><Copy size={16} aria-hidden="true"/>Copy script</button></div><Field label="Full script" hint="Scene timings update automatically as you edit the storyboard."><textarea ref={copyRef} className="rl-script" rows={22} value={reelScript(project)} readOnly dir="auto"/></Field></section>}
      </div><aside className="rl-preview" aria-label="Storyboard preview"><div className="rl-preview-heading"><span><PlatformIcon size={18} aria-hidden="true"/>{REEL_PLATFORMS[project.platform]}</span><small>9:16</small></div><div className="rl-screen"><Frame scene={previewScene} language={project.language}/></div><div className="rl-player"><button className="rl-icon" aria-label={playing?'Pause storyboard':'Play storyboard'} onClick={togglePlayback}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><div className="rl-player-progress" aria-hidden="true"><span style={{width:`${(position??scene.start)/duration*100}%`}}/></div><span>{timecode(position??scene.start)} / {timecode(duration)}</span><button className="rl-icon" aria-label="Restart storyboard" onClick={()=>{setPlaying(false);setPosition(null);setSelected(0);}}><RotateCcw size={17}/></button></div><div className="rl-preview-caption"><span className="rl-eyebrow">{playing?'Playing storyboard':`Frame ${previewIndex+1} of ${project.scenes.length}`}</span><p><Mic size={15} aria-hidden="true"/><span dir={project.language==='ar'?'rtl':'auto'}>{previewScene.voiceover||'Add a voiceover in the scene editor.'}</span></p></div><p className="rl-help">Timed storyboard only. No video, recorded voice or music is generated.</p><button className="rl-text-button rl-copy-script" onClick={copy}><Copy size={16} aria-hidden="true"/>Copy full script</button></aside></div>
    </>}
    <footer className="rl-footer"><img src="/logo-transparent.png" alt="" width="18" height="18"/><span>Plan here. Produce when you are ready.</span><span>Your connected accounts are untouched.</span></footer>
  </main>;
}
