export const RESERVATION_STORAGE_KEY='tw_preview_reservations:v1';
export const RESERVATION_STATUSES=['pending','confirmed','seated','completed','waitlist','no_show','cancelled'];

export const RESERVATION_DAYS=[
  {id:'2026-09-02',weekday:'Wed',day:'02',month:'Sep',label:'Today'},
  {id:'2026-09-03',weekday:'Thu',day:'03',month:'Sep',label:'Tomorrow'},
  {id:'2026-09-04',weekday:'Fri',day:'04',month:'Sep',label:'Friday'},
  {id:'2026-09-05',weekday:'Sat',day:'05',month:'Sep',label:'Saturday'},
  {id:'2026-09-06',weekday:'Sun',day:'06',month:'Sep',label:'Sunday'},
  {id:'2026-09-07',weekday:'Mon',day:'07',month:'Sep',label:'Monday'},
];

export const RESERVATION_SEED={
  settings:{enabled:true,requiresApproval:false,slotMinutes:30,turnMinutes:90,maxParty:8,open:'12:00',close:'23:00',minNoticeMinutes:120,advanceDays:90,concierge:true,holdMinutes:15,whatsappConfirmation:true,hostPin:'2915'},
  bookings:[
    {id:'RSV-208',day:'2026-09-02',guest:'Layla Al Zayani',initials:'LZ',time:'19:00',party:2,status:'seated',tableId:'terrace-2',area:'Terrace',phone:'••• 2184',source:'AI Concierge',occasion:'Anniversary',note:'Quiet table by the water.',visits:6,spend:'BHD 286',tags:['VIP','No shellfish']},
    {id:'RSV-209',day:'2026-09-02',guest:'Hassan Mahmood',initials:'HM',time:'19:15',party:4,status:'confirmed',tableId:'dining-4',area:'Dining room',phone:'••• 9031',source:'Booking link',occasion:'Dinner',note:'High chair needed.',visits:2,spend:'BHD 94',tags:['High chair']},
    {id:'RSV-210',day:'2026-09-02',guest:'Sara Ebrahim',initials:'SE',time:'19:30',party:6,status:'pending',tableId:'',area:'Any area',phone:'••• 7760',source:'Instagram bio',occasion:'Birthday',note:'Bringing a small cake. Needs host approval.',visits:1,spend:'New guest',tags:['Birthday','Needs reply']},
    {id:'RSV-211',day:'2026-09-02',guest:'Dana Mahmood',initials:'DM',time:'20:00',party:2,status:'confirmed',tableId:'terrace-4',area:'Terrace',phone:'••• 1083',source:'QR at hotel',occasion:'Date night',note:'Prefers outside if weather allows.',visits:4,spend:'BHD 172',tags:['Terrace']},
    {id:'RSV-212',day:'2026-09-02',guest:'Mariam Fakhro',initials:'MF',time:'20:30',party:3,status:'confirmed',tableId:'garden-3',area:'Garden',phone:'••• 4812',source:'AI Concierge',occasion:'Dinner',note:'Gluten-free guest in the party.',visits:3,spend:'BHD 138',tags:['Gluten free']},
    {id:'RSV-213',day:'2026-09-02',guest:'Yousef Kanoo',initials:'YK',time:'21:00',party:2,status:'waitlist',tableId:'',area:'Terrace',phone:'••• 9904',source:'Walk-in',occasion:'Dinner',note:'Happy to wait at the bar.',visits:8,spend:'BHD 364',tags:['VIP','Waitlist']},
    {id:'RSV-214',day:'2026-09-02',guest:'Ali Janahi',initials:'AJ',time:'21:30',party:5,status:'confirmed',tableId:'dining-6',area:'Dining room',phone:'••• 7251',source:'Booking link',occasion:'Business dinner',note:'One vegetarian guest.',visits:5,spend:'BHD 244',tags:['Business']},
    {id:'RSV-215',day:'2026-09-02',guest:'Noor Al Sayed',initials:'NS',time:'22:00',party:2,status:'confirmed',tableId:'bar-2',area:'Bar',phone:'••• 3327',source:'Instagram bio',occasion:'Late dinner',note:'No special requests.',visits:2,spend:'BHD 81',tags:[]},
    {id:'RSV-301',day:'2026-09-03',guest:'Fatima Al Arrayed',initials:'FA',time:'19:30',party:4,status:'confirmed',tableId:'terrace-4',area:'Terrace',phone:'••• 6671',source:'Booking link',occasion:'Family dinner',note:'Window-side table if available.',visits:3,spend:'BHD 128',tags:['Terrace']},
    {id:'RSV-302',day:'2026-09-03',guest:'Omar Bukannan',initials:'OB',time:'20:30',party:2,status:'pending',tableId:'',area:'Any area',phone:'••• 1472',source:'AI Concierge',occasion:'Dinner',note:'Awaiting confirmation.',visits:1,spend:'New guest',tags:['Needs reply']},
  ],
  spaces:[
    {id:'waterfront',name:'Waterfront terrace',type:'outdoor'},
    {id:'main',name:'Main dining room',type:'indoor'},
    {id:'garden',name:'Garden',type:'outdoor'},
    {id:'upper',name:'Upper floor',type:'floor'},
  ],
  tables:[
    {id:'terrace-2',spaceId:'waterfront',name:'T2',area:'Terrace',seats:2,shape:'round',x:18,y:30,outOfService:false},
    {id:'terrace-4',spaceId:'waterfront',name:'T4',area:'Terrace',seats:4,shape:'round',x:58,y:46,outOfService:false},
    {id:'garden-3',spaceId:'garden',name:'G3',area:'Garden',seats:4,shape:'round',x:22,y:28,outOfService:false},
    {id:'garden-6',spaceId:'garden',name:'G6',area:'Garden',seats:6,shape:'long',x:58,y:55,outOfService:false},
    {id:'dining-2',spaceId:'main',name:'D2',area:'Dining room',seats:2,shape:'square',x:13,y:25,outOfService:false},
    {id:'dining-4',spaceId:'main',name:'D4',area:'Dining room',seats:4,shape:'square',x:45,y:25,outOfService:false},
    {id:'dining-6',spaceId:'main',name:'D6',area:'Dining room',seats:6,shape:'long',x:60,y:59,outOfService:false},
    {id:'bar-2',spaceId:'main',name:'B2',area:'Bar',seats:2,shape:'round',x:18,y:67,outOfService:false},
  ],
};

const clone=value=>JSON.parse(JSON.stringify(value));
const clean=(value,fallback,max=120)=>typeof value==='string'?(value.trim().slice(0,max)||fallback):fallback;
const inferSpaceId=table=>{const hint=`${table?.id||''} ${table?.area||''}`.toLowerCase();if(hint.includes('garden'))return'garden';if(hint.includes('dining')||hint.includes('bar'))return'main';if(hint.includes('upper'))return'upper';return'waterfront';};

export function normalizeReservationPreview(value){
  const base=clone(RESERVATION_SEED),settings=value?.settings||{},bookings=Array.isArray(value?.bookings)?value.bookings.slice(0,80):base.bookings;
  return{
    settings:{enabled:settings.enabled!==false,requiresApproval:!!settings.requiresApproval,slotMinutes:[15,30,45,60].includes(Number(settings.slotMinutes))?Number(settings.slotMinutes):30,turnMinutes:[60,75,90,105,120,150].includes(Number(settings.turnMinutes))?Number(settings.turnMinutes):90,maxParty:Math.max(1,Math.min(30,Number(settings.maxParty)||8)),open:clean(settings.open,'12:00',5),close:clean(settings.close,'23:00',5),minNoticeMinutes:[0,30,60,90,120,180,240,480,1440].includes(Number(settings.minNoticeMinutes))?Number(settings.minNoticeMinutes):120,advanceDays:[1,7,14,30,60,90,180,365].includes(Number(settings.advanceDays))?Number(settings.advanceDays):90,concierge:settings.concierge!==false,holdMinutes:[5,10,15,20,30].includes(Number(settings.holdMinutes))?Number(settings.holdMinutes):15,whatsappConfirmation:settings.whatsappConfirmation!==false,hostPin:/^\d{4}$/.test(String(settings.hostPin||''))?String(settings.hostPin):'2915'},
    bookings:bookings.map((booking,index)=>{const guest=clean(booking?.guest,'Guest',70).replace(/\bDana Al Khalifa\b/gi,'Dana Mahmood'),parts=guest.split(/\s+/).filter(Boolean);return{id:clean(booking?.id,`RSV-${300+index}`,20),day:RESERVATION_DAYS.some(day=>day.id===booking?.day)?booking.day:RESERVATION_DAYS[0].id,guest,firstName:clean(booking?.firstName,parts[0]||'Guest',40),lastName:clean(booking?.lastName,parts.slice(1).join(' ')||'Guest',50).replace(/^Al Khalifa$/i,'Mahmood'),initials:guest==='Dana Mahmood'?'DM':clean(booking?.initials,'G',3),time:/^([01]\d|2[0-3]):[0-5]\d$/.test(String(booking?.time||''))?booking.time:'19:00',party:Math.max(1,Math.min(30,Number(booking?.party)||2)),status:RESERVATION_STATUSES.includes(booking?.status)?booking.status:'confirmed',tableId:clean(booking?.tableId,'',30),area:clean(booking?.area,'Any area',40),phone:clean(booking?.phone,'••• 0000',30),countryCode:clean(booking?.countryCode,'+973',5),phoneNumber:clean(booking?.phoneNumber,'',20),source:clean(booking?.source,'Booking link',40),occasion:clean(booking?.occasion,'Dinner',50),request:clean(booking?.request,booking?.note||'No special requests.',220),note:clean(booking?.note,'No special requests.',220),visits:Math.max(0,Number(booking?.visits)||0),spend:clean(booking?.spend,'New guest',40),whatsappStatus:['queued','sent','none'].includes(booking?.whatsappStatus)?booking.whatsappStatus:'none',tags:Array.isArray(booking?.tags)?booking.tags.slice(0,6).map(tag=>clean(tag,'',30)).filter(Boolean):[]}}),
    spaces:Array.isArray(value?.spaces)&&value.spaces.length?value.spaces.slice(0,12).map((space,index)=>({id:clean(space?.id,`space-${index+1}`,40),name:clean(space?.name,`Space ${index+1}`,60),type:['indoor','outdoor','floor'].includes(space?.type)?space.type:'indoor'})):base.spaces,
    tables:Array.isArray(value?.tables)&&value.tables.length?value.tables.slice(0,40).map((table,index)=>{const shape=['round','square','long'].includes(table?.shape)?table.shape:'round';return{id:clean(table?.id,`table-${index+1}`,30),spaceId:clean(table?.spaceId,inferSpaceId(table),40),name:clean(table?.name,'T',10),area:clean(table?.area,'Dining room',40),seats:Math.max(1,Math.min(20,Number(table?.seats)||2)),shape,width:Math.max(58,Math.min(180,Number(table?.width)||(shape==='long'?124:82))),depth:Math.max(54,Math.min(132,Number(table?.depth)||(shape==='long'?72:82))),x:Math.max(2,Math.min(88,Number(table?.x)||12+(index%4)*22)),y:Math.max(5,Math.min(82,Number(table?.y)||18+Math.floor(index/4)*28)),outOfService:!!table?.outOfService}}):base.tables.map(table=>({...table,width:table.shape==='long'?124:82,depth:table.shape==='long'?72:82})),
  };
}

export function readReservationPreview(store=typeof window!=='undefined'?window.localStorage:null){if(!store)return{data:normalizeReservationPreview(RESERVATION_SEED),error:''};try{const raw=store.getItem(RESERVATION_STORAGE_KEY);return{data:raw?normalizeReservationPreview(JSON.parse(raw)):normalizeReservationPreview(RESERVATION_SEED),error:''};}catch(_){return{data:normalizeReservationPreview(RESERVATION_SEED),error:'Saved reservation changes could not be read. The sample service is still available.'};}}
export function saveReservationPreview(data,store=typeof window!=='undefined'?window.localStorage:null){if(!store)return{ok:false,error:'Browser storage is unavailable. Keep this page open to preserve your changes.'};try{const normalized=normalizeReservationPreview(data);store.setItem(RESERVATION_STORAGE_KEY,JSON.stringify(normalized));return{ok:true,data:normalized,error:''};}catch(_){return{ok:false,error:'Reservation changes could not be saved in this browser. Your open changes are still here.'};}}
export function reservationSummary(bookings,day){const list=bookings.filter(booking=>booking.day===day&&booking.status!=='cancelled');return{bookings:list.length,covers:list.reduce((sum,booking)=>sum+booking.party,0),confirmed:list.filter(booking=>booking.status==='confirmed').length,pending:list.filter(booking=>booking.status==='pending').length,seated:list.filter(booking=>booking.status==='seated').length,waitlist:list.filter(booking=>booking.status==='waitlist').length};}
export function setReservationStatus(bookings,id,status){if(!RESERVATION_STATUSES.includes(status))return bookings;return bookings.map(booking=>booking.id===id?{...booking,status}:booking);}
export function assignReservationTable(bookings,id,tableId,tables){const table=tables.find(item=>item.id===tableId);return bookings.map(booking=>booking.id===id?{...booking,tableId:tableId||'',area:table?.area||booking.area}:booking);}
export function addPreviewReservation(data,input={},now=Date.now()){const party=Math.max(1,Math.min(30,Number(input.party)||2)),fallbackGuest=clean(input.guest,'Preview Guest',70),fallbackParts=fallbackGuest.split(/\s+/).filter(Boolean),firstName=clean(input.firstName,fallbackParts[0]||'Preview',40),lastName=clean(input.lastName,fallbackParts.slice(1).join(' ')||'Guest',50),guest=`${firstName} ${lastName}`.trim(),initials=`${firstName[0]||'G'}${lastName[0]||''}`.toUpperCase(),countryCode=clean(input.countryCode,'+973',5),phoneNumber=String(input.phoneNumber||'').replace(/[^0-9]/g,'').slice(0,15),request=clean(input.request||input.note,'No special requests.',220);const booking={id:`RSV-${String(now).slice(-3)}`,day:RESERVATION_DAYS.some(day=>day.id===input.day)?input.day:RESERVATION_DAYS[0].id,guest,firstName,lastName,initials,time:/^([01]\d|2[0-3]):[0-5]\d$/.test(String(input.time||''))?input.time:'20:00',party,status:data.settings.requiresApproval?'pending':'confirmed',tableId:'',area:clean(input.area,'Any area',40),phone:phoneNumber?`${countryCode} ${phoneNumber}`:'••• 2026',countryCode,phoneNumber,source:clean(input.source,'Guest booking preview',50),occasion:clean(input.occasion,'Dinner',50),request,note:request,visits:1,spend:'New guest',whatsappStatus:data.settings.whatsappConfirmation&&phoneNumber?'queued':'none',tags:data.settings.requiresApproval?['Needs reply']:[]};return{...data,bookings:[booking,...data.bookings]};}

export function addReservationSpace(data,input={},now=Date.now()){if(data.spaces.length>=12)return data;const space={id:`space-${now}`,name:clean(input.name,`Space ${data.spaces.length+1}`,60),type:['indoor','outdoor','floor'].includes(input.type)?input.type:'indoor'};return{...data,spaces:[...data.spaces,space]};}
export function updateReservationSpace(data,id,patch){return{...data,spaces:data.spaces.map(space=>space.id===id?{...space,...patch}:space)};}
export function removeReservationSpace(data,id){if(data.spaces.length<=1)return data;const fallback=data.spaces.find(space=>space.id!==id),removedTableIds=new Set(data.tables.filter(table=>table.spaceId===id).map(table=>table.id));return{...data,spaces:data.spaces.filter(space=>space.id!==id),tables:data.tables.filter(table=>table.spaceId!==id),bookings:data.bookings.map(booking=>removedTableIds.has(booking.tableId)?{...booking,tableId:'',area:fallback?.name||'Any area'}:booking)};}
export function addReservationTable(data,spaceId,now=Date.now()){if(data.tables.length>=40||!data.spaces.some(space=>space.id===spaceId))return data;const peers=data.tables.filter(table=>table.spaceId===spaceId),index=peers.length,table={id:`table-${now}`,spaceId,name:`T${index+1}`,area:data.spaces.find(space=>space.id===spaceId)?.name||'Dining room',seats:2,shape:'square',width:82,depth:82,x:10+(index%4)*22,y:16+Math.floor(index/4)*28,outOfService:false};return{...data,tables:[...data.tables,table]};}
export function updateReservationTable(data,id,patch){return{...data,tables:data.tables.map(table=>table.id===id?{...table,...patch,width:patch.width===undefined?table.width:Math.max(58,Math.min(180,Number(patch.width))),depth:patch.depth===undefined?table.depth:Math.max(54,Math.min(132,Number(patch.depth))),x:patch.x===undefined?table.x:Math.max(2,Math.min(88,Number(patch.x))),y:patch.y===undefined?table.y:Math.max(5,Math.min(82,Number(patch.y)))}:table)};}
export function removeReservationTable(data,id){return{...data,tables:data.tables.filter(table=>table.id!==id),bookings:data.bookings.map(booking=>booking.tableId===id?{...booking,tableId:'',area:'Any area'}:booking)};}

