import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Bookmark,Check,ChevronRight,Clock,FileText,Moon,Plus,RefreshCw,Search,Sparkles,Sun,X} from 'lucide-react';
import {Artwork} from './CalendarExperience';
import {SAMPLE_SUGGESTED_IDEAS,SAMPLE_SUGGESTED_SOURCES,SUGGESTED_CATEGORIES,filterSuggestedIdeas,readSuggestedRoute,readSuggestedSaved,suggestedIdeaById,toggleSuggestedSaved} from './suggestedPreviewModel';
import './suggested-experience.css';

// Live RSS items have no category and no `why` array, so filterSuggestedIdeas
// (which spreads idea.why) would throw on them. Live mode searches only real fields.
const filterLiveIdeas=(ideas,{query='',savedOnly=false,saved=[]}={})=>{const needle=String(query||'').trim().toLowerCase(),savedSet=new Set(saved);return ideas.filter(idea=>(!savedOnly||savedSet.has(idea.id))&&(!needle||[idea.title,idea.source,idea.snippet].some(value=>String(value||'').toLowerCase().includes(needle))));};

const cleanHost=value=>{try{return new URL(/^https?:\/\//.test(value)?value:`https://${value}`).hostname.replace(/^www\./,'');}catch(_){return'';}};

export default function SuggestedExperience({dark=false,setDark=()=>{},mobileWeb=false,onOpenPublisher=()=>{},onOpenStudio=()=>{},liveIdeas=null,liveSources=null,clientName='',liveError='',liveLoading=false,savedIds=null,onToggleSaved=null,onAddSource=null,onRemoveSource=null,onRefresh=null}){
  // Only title, link, snippet, source, date and image come back from the feeds. Every
  // other field the design shows (rank, signal, moment, channel, timing, why, opener)
  // has no real source, so it stays behind this flag rather than being guessed.
  const live=liveIdeas!==null&&liveIdeas!==undefined,brand=live?clientName:'Marina Social Club';
  const initial=readSuggestedRoute(window.location.search),stored=readSuggestedSaved();
  const dashboardIdea=(()=>{try{const id=sessionStorage.getItem('tw_suggested_dashboard_idea')||'';return suggestedIdeaById(id)?id:'';}catch(_){return'';}})();
  const [route,setRoute]=useState(initial),[savedLocal,setSaved]=useState(stored.items),[sourcesLocal,setSources]=useState(SAMPLE_SUGGESTED_SOURCES),[selectedId,setSelectedId]=useState(initial.idea||dashboardIdea||SAMPLE_SUGGESTED_IDEAS[0].id),[sourceOpen,setSourceOpen]=useState(false),[sourceValue,setSourceValue]=useState(''),[notice,setNotice]=useState(''),[localError,setError]=useState(stored.error);
  const ideas=live?liveIdeas:SAMPLE_SUGGESTED_IDEAS,saved=live?(savedIds||[]):savedLocal,sources=live?(liveSources||[]):sourcesLocal,error=live?liveError:localError;
  const shown=useMemo(()=>live?filterLiveIdeas(ideas,{...route,saved}):filterSuggestedIdeas(ideas,{...route,saved}),[live,ideas,route,saved]);
  const selected=suggestedIdeaById(selectedId,ideas)||shown[0]||ideas[0];
  useEffect(()=>{if(shown.length&&!shown.some(idea=>idea.id===selectedId))setSelectedId(shown[0].id);},[shown,selectedId]);
  useEffect(()=>{if(!dashboardIdea)return;try{sessionStorage.removeItem('tw_suggested_dashboard_idea');const url=new URL(window.location.href);url.searchParams.set('idea',dashboardIdea);window.history.replaceState({},'',url);}catch(_){}},[]);
  useEffect(()=>{const onPop=()=>{const next=readSuggestedRoute(window.location.search);setRoute(next);if(next.idea)setSelectedId(next.idea);};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
  function update(next){const value={...route,...next};setRoute(value);const url=new URL(window.location.href);value.category==='all'?url.searchParams.delete('ideaType'):url.searchParams.set('ideaType',value.category);value.query?url.searchParams.set('ideaSearch',value.query):url.searchParams.delete('ideaSearch');value.savedOnly?url.searchParams.set('ideaView','saved'):url.searchParams.delete('ideaView');window.history.replaceState({},'',url);setNotice('');}
  function choose(id){setSelectedId(id);const url=new URL(window.location.href);url.searchParams.set('idea',id);window.history.replaceState({},'',url);}
  function saveIdea(){if(live){if(onToggleSaved){const next=onToggleSaved(selected);setNotice(next&&next.saved?'Article saved.':'Article removed from saved.');}return;}const response=toggleSuggestedSaved(selected.id,saved);setSaved(response.items);setError(response.error);if(response.ok)setNotice(response.items.includes(selected.id)?'Idea saved to your briefing.':'Idea removed from saved.');}
  function refresh(){if(onRefresh){onRefresh();setNotice('');return;}setNotice('Briefing refreshed. The sample sources are up to date.');}
  function addSource(){const host=cleanHost(sourceValue.trim());if(!host){setError('Enter a website address, such as example.com.');return;}if(sources.some(source=>source.name===host)){setSourceValue('');setNotice('That source is already on the shelf.');return;}if(live){if(onAddSource){const result=onAddSource(sourceValue.trim());setSourceValue('');setNotice(result&&result.error?'':`${host} added.`);}return;}setSources(current=>[...current,{id:`local-${Date.now()}`,name:host,detail:'Added to this browser preview',active:true}]);setSourceValue('');setError('');setNotice(`${host} added to this preview. No source was connected.`);}
  function draft(){try{live?(sessionStorage.setItem('tw_studio_caption',selected.title+(selected.link?`\n\n${selected.link}`:'')),sessionStorage.setItem('tw_studio_aitopic',selected.title)):(sessionStorage.setItem('tw_studio_caption',selected.caption),sessionStorage.setItem('tw_studio_aitopic',selected.angle));}catch(_){}onOpenPublisher(selected);}
  function develop(){try{live?(sessionStorage.setItem('tw_studio_caption',selected.title+(selected.link?`\n\n${selected.link}`:'')),sessionStorage.setItem('tw_studio_aitopic',selected.title)):(sessionStorage.setItem('tw_studio_imgprompt',`Create a ${selected.format} for Marina Social Club. ${selected.angle}`),sessionStorage.setItem('tw_studio_aitopic',selected.title));}catch(_){}onOpenStudio(selected);}
  return <main className="tw-suggested-desk" data-suggested-theme={dark?'dark':'light'}>
    <div className="sg-preview-line"><span>{live?(liveLoading?'Loading the latest articles…':`${ideas.length} ${ideas.length===1?'article':'articles'} from ${sources.length} ${sources.length===1?'feed':'feeds'}`):'Design preview · Editorial briefing · Sample signals'}</span><button className="sg-icon" aria-label={dark?'Use light Ideas for you theme':'Use dark Ideas for you theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div>
    <header className="sg-heading"><div><span className="sg-kicker"><img src="/logo-transparent.png" alt="" width="22" height="22"/>{brand?`Ideas for you / ${brand}`:'Ideas for you'}</span><h1>Ideas worth making.</h1><p>{live?'Fresh stories from your sources — one tap to a draft.':'A daily edit of timely angles, ranked for this brand.'}</p><div className="sg-facts"><span><strong>{ideas.length}</strong> {live?(ideas.length===1?'article':'articles'):'opportunities'}</span><span><strong>{sources.length}</strong> sources</span><span><strong>{saved.length}</strong> saved</span></div></div><div className="sg-heading-actions"><button className="sg-text-button" onClick={()=>setSourceOpen(value=>!value)} aria-expanded={sourceOpen}><FileText size={17}/>Source shelf</button><button className="sg-button sg-primary" onClick={refresh}><RefreshCw size={17}/>Refresh briefing</button></div></header>
    <div className="sg-feedback" role="status">{notice}</div>{error&&<p className="sg-error" role="alert">{error}</p>}
    {sourceOpen&&<section className="sg-sources" aria-label="Source shelf"><div className="sg-source-list">{sources.map(source=><div key={source.id}><span className="sg-source-dot"/><span><strong>{source.name}</strong><small>{source.detail}</small></span><button aria-label={`Remove ${source.name}`} onClick={()=>setSources(current=>current.filter(item=>item.id!==source.id))}><X size={15}/></button></div>)}</div><div className="sg-source-add"><label htmlFor="sg-source-url">Add a website or feed</label><div><input id="sg-source-url" value={sourceValue} onChange={event=>setSourceValue(event.target.value.slice(0,200))} onKeyDown={event=>{if(event.key==='Enter')addSource();}} placeholder="example.com/feed"/><button onClick={addSource}><Plus size={15}/>Add source</button></div><small>{live?'Feeds are stored in this browser for this client.':'Sources added here stay in this browser preview.'}</small></div></section>}
    <section className="sg-controls" aria-label="Idea filters"><label className="sg-search"><Search size={17}/><span className="sg-sr-only">Search ideas</span><input type="search" value={route.query} placeholder="Search ideas" onChange={event=>update({query:event.target.value.slice(0,80)})}/>{route.query&&<button aria-label="Clear idea search" onClick={()=>update({query:''})}><X size={16}/></button>}</label>{!live&&<div className="sg-tabs">{SUGGESTED_CATEGORIES.map(([id,label])=><button key={id} aria-pressed={route.category===id} onClick={()=>update({category:id})}>{label}</button>)}</div>}<button className="sg-saved-filter" aria-pressed={route.savedOnly} onClick={()=>update({savedOnly:!route.savedOnly})}><Bookmark size={16} fill={route.savedOnly?'currentColor':'none'}/>Saved <span>{saved.length}</span></button></section>
    <div className={`sg-workbench${shown.length?'':' sg-workbench-empty'}`}>
      <section className="sg-queue" aria-labelledby="sg-queue-title"><div className="sg-section-heading"><span className="sg-eyebrow">{live?'From your feeds':'Today’s briefing'}</span><h2 id="sg-queue-title">{live?`${shown.length} ${shown.length===1?'article':'articles'}`:`${shown.length} ${shown.length===1?'opportunity':'opportunities'}, ranked`}</h2></div>{shown.length?<ol>{shown.map(idea=><li key={idea.id}><button aria-pressed={selected.id===idea.id} aria-label={`Open idea ${idea.title}`} onClick={()=>choose(idea.id)}>{!live&&<span className="sg-rank">{String(idea.priority).padStart(2,'0')}</span>}<span className="sg-idea-copy"><span className="sg-idea-meta">{!live&&<strong>{idea.signal}</strong>}<small>{[idea.source,idea.published].filter(Boolean).join(' · ')}</small></span><b>{idea.title}</b><span className="sg-idea-foot">{!live&&<small>{idea.format} · {idea.platform}</small>}{saved.includes(idea.id)&&<span><Bookmark size={12} fill="currentColor"/>Saved</span>}</span></span><ChevronRight size={18}/></button></li>)}</ol>:<div className="sg-empty"><Search size={30}/><h3>{route.savedOnly?(live?'No saved articles match this view.':'No saved ideas match this view.'):live&&!sources.length?'No feeds added yet.':live&&!ideas.length?'No articles found in these feeds.':'No ideas match these filters.'}</h3><p>{live&&!sources.length?'Open the source shelf and add an RSS feed to start.':live&&!ideas.length?'Check that each source is a valid RSS feed address.':'Clear the search or open the full briefing.'}</p>{(!live||!!ideas.length)&&<button className="sg-text-button" onClick={()=>update({category:'all',query:'',savedOnly:false})}>Clear filters</button>}</div>}</section>
      {!!shown.length&&<aside className="sg-pitch" aria-labelledby="sg-pitch-title"><div className="sg-pitch-top"><div>{!live&&<span>{selected.moment}</span>}<small>{[selected.source,selected.published].filter(Boolean).join(' · ')}</small></div><button className="sg-save" aria-label={saved.includes(selected.id)?'Remove idea from saved':'Save idea'} aria-pressed={saved.includes(selected.id)} onClick={saveIdea}><Bookmark size={19} fill={saved.includes(selected.id)?'currentColor':'none'}/></button></div>{live?(selected.image?<figure><img src={selected.image} alt="" loading="lazy"/></figure>:null):<figure><Artwork post={{art:selected.art}} compact/><figcaption>{selected.format} direction</figcaption></figure>}<div className="sg-pitch-copy"><span className="sg-eyebrow">{live?'From the article':'Recommended angle'}</span><h2 id="sg-pitch-title">{selected.title}</h2><p>{live?selected.snippet:selected.angle}</p></div>{!live&&<><section className="sg-why"><h3>Why it fits Marina</h3><ul>{selected.why.map(reason=><li key={reason}><Check size={14}/><span>{reason}</span></li>)}</ul></section><section className="sg-execution"><div><span>Format</span><strong>{selected.format}</strong></div><div><span>Channel</span><strong>{selected.platform}</strong></div><div><span>Best window</span><strong><Clock size={13}/>{selected.timing}</strong></div></section><blockquote><span>Opening line</span><p>“{selected.opener}”</p></blockquote></>}<div className="sg-pitch-actions">{!mobileWeb&&<button className="sg-button sg-primary" onClick={draft}><ArrowUpRight size={17}/>Turn into a post</button>}<button className="sg-button" onClick={develop}><Sparkles size={17}/>Develop in AI Studio</button>{live&&selected.link&&<a className="sg-button" href={selected.link} target="_blank" rel="noreferrer"><ArrowUpRight size={17}/>Read the article</a>}</div>{!live&&<p className="sg-local-note">Sample briefing. Saving and source changes stay in this browser preview.</p>}</aside>}
    </div>
    <footer className="sg-footer"><span>Signal, angle, execution.</span><span>{brand?`Prepared for ${brand}`:'Prepared with Tawaslo'}</span></footer>
  </main>;
}
