import {cloneElement,useEffect,useId,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,Copy,Eye,FileText,Moon,Plus,Sun} from 'lucide-react';
import {DEFAULT_PROPOSAL,BLANK_PROPOSAL,PROPOSAL_GOALS,PROPOSAL_TYPES,PROPOSAL_PLATFORMS,PROPOSAL_STORAGE_KEY,proposalDocument,proposalText,readProposals,saveProposal,validateProposal,readProposalRoute,readableOnAccent} from './proposalPreviewModel';
import './win-clients-experience.css';

function Field({label,error,hint,children}){const id=useId(),described=[error?`${id}-error`:null,hint?`${id}-hint`:null].filter(Boolean).join(' ')||undefined;return <div className="wp-field"><label htmlFor={id}>{label}</label>{cloneElement(children,{id,'aria-invalid':error?true:undefined,'aria-describedby':described})}{error&&<small id={`${id}-error`} className="wp-field-error">{error}</small>}{hint&&!error&&<small id={`${id}-hint`}>{hint}</small>}</div>}

function ProposalDocument({fields,prospect=false}){const doc=proposalDocument(fields),onAccent=readableOnAccent(fields.accent);return <article className="wp-document" data-paper-theme={fields.presentationTheme} style={{'--wp-brand':fields.accent,'--wp-on-brand':onAccent}} aria-label={`Proposal for ${fields.prospectName||'prospect'}`}>
  <header><span>{fields.agencyName||'Your agency'}</span><span>Social direction / 30 days</span></header>
  <div className="wp-cover"><span>Prepared for</span><h2>{fields.prospectName||'Your next client'}</h2><p>{doc.headline}</p></div>
  <div className="wp-letter"><p>{doc.intro}</p><section><span>The opportunity</span><h3>{doc.opportunity}</h3></section><section><span>The first 30 days</span><ol>{doc.plan.map(item=><li key={item}>{item}</li>)}</ol></section><section className="wp-offer"><span>The offer</span><p>{doc.offer}</p>{doc.price&&<strong>{doc.price}</strong>}</section></div>
  <footer><div><span>Next step</span><strong>{doc.cta}</strong></div><span className="wp-document-cta" aria-label={prospect?'Proposal call to action preview':'Sample call to action'}>{prospect?'I’m interested':'Prospect button'}</span></footer>
</article>}

export default function WinClientsExperience({dark=false,setDark=()=>{},agencyName='Your agency'}){
  const colorId=useId();
  const initialRoute=readProposalRoute(window.location.search),initialLibrary=readProposals(),initialSaved=initialLibrary.items.find(item=>item.id===initialRoute.id);
  const [route,setRoute]=useState(initialRoute),[form,setForm]=useState(()=>initialSaved?initialSaved.fields:{...DEFAULT_PROPOSAL,agencyName:agencyName||DEFAULT_PROPOSAL.agencyName});
  const [sourceId,setSourceId]=useState(initialSaved?.sourceId||''),[baseline,setBaseline]=useState(()=>JSON.stringify(initialSaved?.fields||{...DEFAULT_PROPOSAL,agencyName:agencyName||DEFAULT_PROPOSAL.agencyName}));
  const [saved,setSaved]=useState(initialLibrary),[errors,setErrors]=useState({}),[notice,setNotice]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState('');
  const errorRef=useRef(null),libraryRef=useRef(null),copyRef=useRef(null);
  const dirty=JSON.stringify(form)!==baseline;
  useEffect(()=>{const onPop=()=>{const next=readProposalRoute(window.location.search);setRoute(next);setPending('');if(next.id){const item=readProposals().items.find(savedItem=>savedItem.id===next.id);if(item)open(item,false);}};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
  useEffect(()=>{const refresh=()=>setSaved(readProposals());const sync=e=>{if(e.key===PROPOSAL_STORAGE_KEY||e.key===null)refresh();};window.addEventListener('focus',refresh);window.addEventListener('storage',sync);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('storage',sync);};},[]);
  useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>{requestAnimationFrame(()=>{const scroller=document.querySelector('.tw-scroll-area');if(scroller)scroller.scrollTop=0;});},[route.view]);
  function update(key,value){setForm(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:undefined}));setNotice('');setError('');}
  function navigate(next,id='',push=false){setRoute({view:next,id});const url=new URL(window.location.href);url.searchParams.set('proposalView',next);id?url.searchParams.set('proposalId',id):url.searchParams.delete('proposalId');window.history[push?'pushState':'replaceState']({},'',url);setError('');setNotice('');}
  function blank(){setForm({...BLANK_PROPOSAL,agencyName:agencyName||DEFAULT_PROPOSAL.agencyName});setSourceId('');setBaseline(JSON.stringify({...BLANK_PROPOSAL,agencyName:agencyName||DEFAULT_PROPOSAL.agencyName}));setErrors({});setPending('');navigate('editor','',true);}
  function request(action){if(dirty){setPending(action);requestAnimationFrame(()=>errorRef.current?.focus());}else action==='new'?blank():navigate('library','',true);}
  function open(item,push=true){setForm({...item.fields});setSourceId(item.sourceId);setBaseline(JSON.stringify(item.fields));setErrors({});setPending('');navigate('editor',item.id,push);requestAnimationFrame(()=>libraryRef.current?.focus());}
  function save(){const response=saveProposal(form,sourceId);if(!response.ok){setErrors(response.errors||{});setError(response.error);requestAnimationFrame(()=>errorRef.current?.focus());return;}setSourceId(response.item.sourceId);setBaseline(JSON.stringify(response.item.fields));setForm(response.item.fields);setSaved({items:response.items,error:''});setErrors({});navigate('editor',response.item.id);setNotice(`Version ${response.item.version} saved in this browser.`);}
  function prospect(){const invalid=validateProposal(form);if(Object.keys(invalid).length){setErrors(invalid);setError('Complete the highlighted fields before previewing the proposal.');requestAnimationFrame(()=>errorRef.current?.focus());return;}navigate('prospect',route.id,true);}
  async function copy(){try{await navigator.clipboard.writeText(proposalText(form));setNotice('Proposal text copied.');setError('');}catch(_){setError('Clipboard access is unavailable. Select the proposal text and copy it manually.');requestAnimationFrame(()=>copyRef.current?.focus());}}
  if(route.view==='prospect')return <main className="tw-win-prospect" data-win-theme={form.presentationTheme}><div className="wp-prospect-bar"><button className="wp-text" onClick={()=>navigate('editor',route.id)}><ArrowLeft size={17} aria-hidden="true"/>Back to editor</button><span>Prospect view · Local design preview</span></div><div className="wp-prospect-stage"><ProposalDocument fields={form} prospect/></div></main>;
  return <main className="tw-win-clients" data-win-theme={dark?'dark':'light'}>
    <div className="wp-preview-line"><span>Design preview · Sample proposal · Nothing sent</span><button className="wp-icon" aria-label={dark?'Use light Win Clients theme':'Use dark Win Clients theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div>
    <header className="wp-heading"><div><span className="wp-kicker"><img src="/logo-transparent.png" alt="" width="22" height="22"/>Agency growth / Proposal desk</span><h1>Win Clients</h1><p>Lead with something useful. Make the next conversation easier.</p></div><div className="wp-heading-actions"><button className="wp-text" onClick={()=>request('library')}><Bookmark size={16} aria-hidden="true"/>Saved proposals <span>{saved.items.length}</span></button><button className="wp-button wp-primary" onClick={()=>request('new')}><Plus size={17} aria-hidden="true"/>New proposal</button></div></header>
    <div className="wp-feedback" role="status">{notice}</div>{(error||saved.error)&&<p className="wp-error" role="alert" ref={errorRef} tabIndex={-1}>{error||saved.error}</p>}
    {pending&&<section className="wp-confirm" aria-label="Unsaved proposal"><h2 ref={errorRef} tabIndex={-1}>Keep your changes?</h2><p>This proposal has edits that are not saved.</p><div><button className="wp-button" onClick={()=>setPending('')}>Keep editing</button><button className="wp-text" onClick={()=>pending==='new'?blank():navigate('library','',true)}>Discard edits</button></div></section>}
    {route.view==='library'?<section className="wp-library" aria-labelledby="wp-library-title"><div className="wp-section-heading"><div><span className="wp-eyebrow">Kept for later</span><h2 id="wp-library-title" ref={libraryRef} tabIndex={-1}>Saved proposals.</h2><p>Every save creates a new version. Nothing is sent from this preview.</p></div><button className="wp-button" onClick={()=>request('new')}><Plus size={17} aria-hidden="true"/>New proposal</button></div>{saved.items.length?<ol>{saved.items.map(item=><li key={item.id}><button onClick={()=>open(item)}><span><strong>{item.fields.prospectName}</strong><small>@{item.fields.handle} · {PROPOSAL_PLATFORMS.find(([id])=>id===item.fields.platform)?.[1]}</small></span><span><small>Version {item.version}</small><ArrowRight size={17} aria-hidden="true"/></span></button></li>)}</ol>:<div className="wp-empty"><FileText size={28} aria-hidden="true"/><h3>No saved proposals yet.</h3><p>Start a proposal, make it relevant to the prospect, then save a version here.</p><button className="wp-button wp-primary" onClick={blank}>Create a proposal</button></div>}</section>:<div className="wp-workspace">
      <form className="wp-editor" onSubmit={e=>{e.preventDefault();save();}} aria-label="Proposal editor"><section><div className="wp-section-title"><span>01</span><div><h2>The prospect</h2><p>Who are you speaking to, and what outcome matters?</p></div></div><div className="wp-two"><Field label="Business name" error={errors.prospectName}><input value={form.prospectName} maxLength={120} onChange={e=>update('prospectName',e.target.value)}/></Field><Field label="Social handle" error={errors.handle}><input value={form.handle} maxLength={40} onChange={e=>update('handle',e.target.value)} placeholder="account.name"/></Field></div><div className="wp-two"><Field label="Platform" error={errors.platform}><select value={form.platform} onChange={e=>update('platform',e.target.value)}>{PROPOSAL_PLATFORMS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="Primary goal" error={errors.goal}><select value={form.goal} onChange={e=>update('goal',e.target.value)}>{PROPOSAL_GOALS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field></div></section>
      <section><div className="wp-section-title"><span>02</span><div><h2>The offer</h2><p>Choose the next step that fits this conversation.</p></div></div><fieldset className="wp-choice"><legend>How do you want to start?</legend>{PROPOSAL_TYPES.map(([id,label])=><label key={id}><input type="radio" name="pitch-type" value={id} checked={form.pitchType===id} onChange={e=>update('pitchType',e.target.value)}/><span>{label}</span></label>)}</fieldset>{form.pitchType==='proposal'&&<div className="wp-price"><Field label="Package name" error={errors.packageName}><input value={form.packageName} maxLength={120} onChange={e=>update('packageName',e.target.value)}/></Field><Field label="Price" error={errors.price}><input inputMode="decimal" value={form.price} onChange={e=>update('price',e.target.value)}/></Field><Field label="Currency" error={errors.currency}><input value={form.currency} maxLength={3} onChange={e=>update('currency',e.target.value.toUpperCase())}/></Field></div>}<Field label="Call to action" error={errors.cta}><input value={form.cta} maxLength={120} onChange={e=>update('cta',e.target.value)}/></Field></section>
      <section><div className="wp-section-title"><span>03</span><div><h2>Your signature</h2><p>The proposal should feel like it came from your agency.</p></div></div><div className="wp-two"><Field label="Agency name" error={errors.agencyName}><input value={form.agencyName} maxLength={120} onChange={e=>update('agencyName',e.target.value)}/></Field><Field label="Prepared by (optional)" error={errors.contactName}><input value={form.contactName} maxLength={120} onChange={e=>update('contactName',e.target.value)}/></Field></div><div className="wp-style-row"><div className="wp-field"><label htmlFor={colorId}>Brand color</label><span className="wp-color-field"><input type="color" aria-label="Choose brand color" value={/^#[0-9a-f]{6}$/i.test(form.accent)?form.accent:'#b43d31'} onChange={e=>update('accent',e.target.value.toUpperCase())}/><input id={colorId} value={form.accent} maxLength={7} aria-invalid={errors.accent?true:undefined} aria-describedby={`${colorId}-${errors.accent?'error':'hint'}`} onChange={e=>update('accent',e.target.value.toUpperCase())}/></span>{errors.accent?<small id={`${colorId}-error`} className="wp-field-error">{errors.accent}</small>:<small id={`${colorId}-hint`}>Choose a color or enter its six-digit HEX code.</small>}</div><fieldset className="wp-appearance"><legend>Proposal appearance</legend><label><input type="radio" name="paper-theme" checked={form.presentationTheme==='light'} onChange={()=>update('presentationTheme','light')}/><span>Light</span></label><label><input type="radio" name="paper-theme" checked={form.presentationTheme==='dark'} onChange={()=>update('presentationTheme','dark')}/><span>Dark</span></label></fieldset></div></section>
      <div className="wp-editor-actions"><button type="submit" className="wp-button wp-primary">{sourceId?'Save new version':'Save proposal'}<Bookmark size={17} aria-hidden="true"/></button><button type="button" className="wp-text" onClick={prospect}><Eye size={17} aria-hidden="true"/>Preview as prospect</button><button type="button" ref={copyRef} className="wp-text" onClick={copy}><Copy size={17} aria-hidden="true"/>Copy proposal text</button></div></form>
      <aside className="wp-preview" aria-labelledby="wp-preview-title"><div className="wp-preview-heading"><div><span className="wp-eyebrow">Live proposal</span><h2 id="wp-preview-title">What the prospect sees.</h2></div><span>{form.presentationTheme==='dark'?'Dark':'Light'} appearance</span></div><ProposalDocument fields={form}/><p className="wp-preview-note">Your edits update here immediately. This local preview does not create a public link or send a message.</p></aside>
    </div>}
    <footer className="wp-footer"><span>Useful first. Specific always.</span><span>Local preview · No database or outreach</span></footer>
  </main>;
}
